// Direct3D 8 COM ABI. Method order is the ABI: never trim or reorder it.

'use strict';

const interfaces = [
  { prefix: 'IDirect3D8', methods: [
    { name: 'QueryInterface',             nargs: 3 },
    { name: 'AddRef',                     nargs: 1, handler: 'dx_com_addref' },
    { name: 'Release',                    nargs: 1, handler: 'dx_com_release_basic' },
    { name: 'RegisterSoftwareDevice',     nargs: 2 },
    { name: 'GetAdapterCount',            nargs: 1 },
    { name: 'GetAdapterIdentifier',       nargs: 4 },
    { name: 'GetAdapterModeCount',        nargs: 2 },
    { name: 'EnumAdapterModes',           nargs: 4 },
    { name: 'GetAdapterDisplayMode',      nargs: 3 },
    { name: 'CheckDeviceType',            nargs: 6 },
    { name: 'CheckDeviceFormat',          nargs: 7 },
    { name: 'CheckDeviceMultiSampleType', nargs: 6 },
    { name: 'CheckDepthStencilMatch',     nargs: 6 },
    { name: 'GetDeviceCaps',              nargs: 4 },
    { name: 'GetAdapterMonitor',          nargs: 2 },
    { name: 'CreateDevice',               nargs: 7, ret: 'HRESULT' },
  ] },
  { prefix: 'IDirect3DDevice8', methods: [
    { name: 'QueryInterface', nargs: 3 },
    { name: 'AddRef', nargs: 1, handler: 'dx_com_addref' },
    { name: 'Release', nargs: 1, handler: 'IDirect3DDevice9_Release' },
    { name: 'TestCooperativeLevel', nargs: 1, handler: 'IDirect3DDevice9_TestCooperativeLevel', ret: 'HRESULT' },
    { name: 'GetAvailableTextureMem', nargs: 1, handler: 'IDirect3DDevice9_GetAvailableTextureMem' },
    { name: 'ResourceManagerDiscardBytes', nargs: 2 },
    { name: 'GetDirect3D', nargs: 2, handler: 'IDirect3DDevice9_GetDirect3D' },
    { name: 'GetDeviceCaps', nargs: 2 },
    { name: 'GetDisplayMode', nargs: 2 },
    { name: 'GetCreationParameters', nargs: 2, handler: 'IDirect3DDevice9_GetCreationParameters' },
    { name: 'SetCursorProperties', nargs: 4, handler: 'IDirect3DDevice9_SetCursorProperties' },
    { name: 'SetCursorPosition', nargs: 4, handler: 'IDirect3DDevice9_SetCursorPosition' },
    { name: 'ShowCursor', nargs: 2, handler: 'IDirect3DDevice9_ShowCursor' },
    { name: 'CreateAdditionalSwapChain', nargs: 3, handler: 'd3d8_unimplemented' },
    { name: 'Reset', nargs: 2, ret: 'HRESULT' },
    { name: 'Present', nargs: 5, handler: 'IDirect3DDevice9_Present', ret: 'HRESULT' },
    { name: 'GetBackBuffer', nargs: 4 },
    { name: 'GetRasterStatus', nargs: 2, handler: 'd3d8_unimplemented' },
    { name: 'SetGammaRamp', nargs: 3 },
    { name: 'GetGammaRamp', nargs: 2 },
    { name: 'CreateTexture', nargs: 8 },
    { name: 'CreateVolumeTexture', nargs: 9, handler: 'd3d8_unimplemented' },
    { name: 'CreateCubeTexture', nargs: 7 },
    { name: 'CreateVertexBuffer', nargs: 6 },
    { name: 'CreateIndexBuffer', nargs: 6 },
    { name: 'CreateRenderTarget', nargs: 7 },
    { name: 'CreateDepthStencilSurface', nargs: 6 },
    { name: 'CreateImageSurface', nargs: 5 },
    { name: 'CopyRects', nargs: 6 },
    { name: 'UpdateTexture', nargs: 3, handler: 'IDirect3DDevice9_UpdateTexture' },
    { name: 'GetFrontBuffer', nargs: 2, handler: 'd3d8_unimplemented' },
    { name: 'SetRenderTarget', nargs: 3 },
    { name: 'GetRenderTarget', nargs: 2 },
    { name: 'GetDepthStencilSurface', nargs: 2},
    { name: 'BeginScene', nargs: 1, handler: 'IDirect3DDevice9_BeginScene' },
    { name: 'EndScene', nargs: 1, handler: 'IDirect3DDevice9_EndScene' },
    { name: 'Clear', nargs: 7, handler: 'IDirect3DDevice9_Clear' },
    { name: 'SetTransform', nargs: 3, handler: 'IDirect3DDevice9_SetTransform' },
    { name: 'GetTransform', nargs: 3, handler: 'IDirect3DDevice9_GetTransform' },
    { name: 'MultiplyTransform', nargs: 3, handler: 'IDirect3DDevice9_MultiplyTransform' },
    { name: 'SetViewport', nargs: 2, handler: 'IDirect3DDevice9_SetViewport' },
    { name: 'GetViewport', nargs: 2, handler: 'IDirect3DDevice9_GetViewport' },
    { name: 'SetMaterial', nargs: 2, handler: 'IDirect3DDevice9_SetMaterial' },
    { name: 'GetMaterial', nargs: 2, handler: 'IDirect3DDevice9_GetMaterial' },
    { name: 'SetLight', nargs: 3, handler: 'IDirect3DDevice9_SetLight' },
    { name: 'GetLight', nargs: 3, handler: 'IDirect3DDevice9_GetLight' },
    { name: 'LightEnable', nargs: 3, handler: 'IDirect3DDevice9_LightEnable' },
    { name: 'GetLightEnable', nargs: 3, handler: 'IDirect3DDevice9_GetLightEnable' },
    { name: 'SetClipPlane', nargs: 3, handler: 'IDirect3DDevice9_SetClipPlane' },
    { name: 'GetClipPlane', nargs: 3, handler: 'IDirect3DDevice9_GetClipPlane' },
    { name: 'SetRenderState', nargs: 3, handler: 'IDirect3DDevice9_SetRenderState' },
    { name: 'GetRenderState', nargs: 3, handler: 'IDirect3DDevice9_GetRenderState' },
    { name: 'BeginStateBlock', nargs: 1, handler: 'IDirect3DDevice9_BeginStateBlock' },
    // A D3D8 state-block token is the D3D9 state-block object's address.
    { name: 'EndStateBlock', nargs: 2, handler: 'IDirect3DDevice9_EndStateBlock' },
    { name: 'ApplyStateBlock', nargs: 2, handler: 'd3d8_ApplyStateBlock' },
    { name: 'CaptureStateBlock', nargs: 2, handler: 'd3d8_CaptureStateBlock' },
    { name: 'DeleteStateBlock', nargs: 2, handler: 'd3d8_DeleteStateBlock' },
    { name: 'CreateStateBlock', nargs: 3, handler: 'IDirect3DDevice9_CreateStateBlock' },
    { name: 'SetClipStatus', nargs: 2, handler: 'IDirect3DDevice9_SetClipStatus' },
    { name: 'GetClipStatus', nargs: 2, handler: 'IDirect3DDevice9_GetClipStatus' },
    { name: 'GetTexture', nargs: 3, handler: 'IDirect3DDevice9_GetTexture' },
    { name: 'SetTexture', nargs: 3, handler: 'IDirect3DDevice9_SetTexture' },
    { name: 'GetTextureStageState', nargs: 4 },
    { name: 'SetTextureStageState', nargs: 4 },
    { name: 'ValidateDevice', nargs: 2, handler: 'IDirect3DDevice9_ValidateDevice' },
    { name: 'GetInfo', nargs: 4, handler: 'd3d8_unimplemented' },
    { name: 'SetPaletteEntries', nargs: 3, handler: 'IDirect3DDevice9_SetPaletteEntries' },
    { name: 'GetPaletteEntries', nargs: 3, handler: 'IDirect3DDevice9_GetPaletteEntries' },
    { name: 'SetCurrentTexturePalette', nargs: 2, handler: 'IDirect3DDevice9_SetCurrentTexturePalette' },
    { name: 'GetCurrentTexturePalette', nargs: 2, handler: 'IDirect3DDevice9_GetCurrentTexturePalette' },
    { name: 'DrawPrimitive', nargs: 4, handler: 'IDirect3DDevice9_DrawPrimitive' },
    { name: 'DrawIndexedPrimitive', nargs: 6 },
    { name: 'DrawPrimitiveUP', nargs: 5, handler: 'IDirect3DDevice9_DrawPrimitiveUP' },
    { name: 'DrawIndexedPrimitiveUP', nargs: 9, handler: 'IDirect3DDevice9_DrawIndexedPrimitiveUP' },
    { name: 'ProcessVertices', nargs: 6, handler: 'd3d8_unimplemented' },
    { name: 'CreateVertexShader', nargs: 5 },
    { name: 'SetVertexShader', nargs: 2 },
    { name: 'GetVertexShader', nargs: 2 },
    { name: 'DeleteVertexShader', nargs: 2 },
    { name: 'SetVertexShaderConstant', nargs: 4, handler: 'd3d8_unimplemented' },
    { name: 'GetVertexShaderConstant', nargs: 4, handler: 'd3d8_unimplemented' },
    { name: 'GetVertexShaderDeclaration', nargs: 4, handler: 'd3d8_unimplemented' },
    { name: 'GetVertexShaderFunction', nargs: 4, handler: 'd3d8_unimplemented' },
    { name: 'SetStreamSource', nargs: 4 },
    { name: 'GetStreamSource', nargs: 4, handler: 'd3d8_unimplemented' },
    { name: 'SetIndices', nargs: 3 },
    { name: 'GetIndices', nargs: 3, handler: 'd3d8_unimplemented' },
    { name: 'CreatePixelShader', nargs: 3 },
    { name: 'SetPixelShader', nargs: 2 },
    { name: 'GetPixelShader', nargs: 2 },
    { name: 'DeletePixelShader', nargs: 2 },
    { name: 'SetPixelShaderConstant', nargs: 4, handler: 'IDirect3DDevice9_SetPixelShaderConstantF' },
    { name: 'GetPixelShaderConstant', nargs: 4, handler: 'IDirect3DDevice9_GetPixelShaderConstantF' },
    { name: 'GetPixelShaderFunction', nargs: 4 },
    { name: 'DrawRectPatch', nargs: 4, handler: 'IDirect3DDevice9_DrawRectPatch' },
    { name: 'DrawTriPatch', nargs: 4, handler: 'IDirect3DDevice9_DrawTriPatch' },
    { name: 'DeletePatch', nargs: 2, handler: 'IDirect3DDevice9_DeletePatch' },
  ] },
  // D3D8 textures share their first fourteen Resource/BaseTexture slots with
  // D3D9, then D3D9 inserts three autogen-mipmap methods.  Keep a real D3D8
  // vtable so GetLevelDesc and every following call cannot slide by 3 slots.
  { prefix: 'IDirect3DTexture8', methods: [
    { name: 'QueryInterface', nargs: 3, handler: 'IDirect3DTexture9_QueryInterface' },
    { name: 'AddRef', nargs: 1, handler: 'IDirect3DTexture9_AddRef' },
    { name: 'Release', nargs: 1, handler: 'IDirect3DTexture9_Release' },
    { name: 'GetDevice', nargs: 2, handler: 'IDirect3DTexture9_GetDevice' },
    { name: 'SetPrivateData', nargs: 5, handler: 'IDirect3DTexture9_SetPrivateData' },
    { name: 'GetPrivateData', nargs: 4, handler: 'IDirect3DTexture9_GetPrivateData' },
    { name: 'FreePrivateData', nargs: 2, handler: 'IDirect3DTexture9_FreePrivateData' },
    { name: 'SetPriority', nargs: 2, handler: 'IDirect3DTexture9_SetPriority' },
    { name: 'GetPriority', nargs: 1, handler: 'IDirect3DTexture9_GetPriority' },
    { name: 'PreLoad', nargs: 1, handler: 'IDirect3DTexture9_PreLoad' },
    { name: 'GetType', nargs: 1, handler: 'IDirect3DTexture9_GetType' },
    { name: 'SetLOD', nargs: 2, handler: 'IDirect3DTexture9_SetLOD' },
    { name: 'GetLOD', nargs: 1, handler: 'IDirect3DTexture9_GetLOD' },
    { name: 'GetLevelCount', nargs: 1, handler: 'IDirect3DTexture9_GetLevelCount' },
    { name: 'GetLevelDesc', nargs: 3},
    { name: 'GetSurfaceLevel', nargs: 3},
    { name: 'LockRect', nargs: 5, handler: 'IDirect3DTexture9_LockRect' },
    { name: 'UnlockRect', nargs: 2, handler: 'IDirect3DTexture9_UnlockRect' },
    { name: 'AddDirtyRect', nargs: 2, handler: 'IDirect3DTexture9_AddDirtyRect' },
  ] },
  // D3D8 surfaces lack D3D9's SetPriority/GetPriority/PreLoad/GetType block,
  // so GetDesc is slot 8 here and slot 12 there, and D3D8's SURFACE_DESC
  // carries Size where D3D9 has MultiSampleQuality. Each slot maps a
  // D3D8 `this` back to its D3D9 identity and reuses that implementation;
  // GetDesc also translates the descriptor.
  { prefix: 'IDirect3DSurface8', methods: [
    { name: 'QueryInterface', nargs: 3 },
    { name: 'AddRef', nargs: 1 },
    { name: 'Release', nargs: 1 },
    { name: 'GetDevice', nargs: 2 },
    { name: 'SetPrivateData', nargs: 5 },
    { name: 'GetPrivateData', nargs: 4 },
    { name: 'FreePrivateData', nargs: 2 },
    { name: 'GetContainer', nargs: 3 },
    { name: 'GetDesc', nargs: 2 },
    { name: 'LockRect', nargs: 4 },
    { name: 'UnlockRect', nargs: 1 },
  ] },
  // D3D8 cube methods retain their own ABI and interface identity.
  { prefix: 'IDirect3DCubeTexture8', methods: [
    { name: 'QueryInterface', nargs: 3 },
    { name: 'AddRef', nargs: 1, handler: 'IDirect3DCubeTexture9_AddRef' },
    { name: 'Release', nargs: 1, handler: 'IDirect3DCubeTexture9_Release' },
    { name: 'GetDevice', nargs: 2, handler: 'IDirect3DCubeTexture9_GetDevice' },
    { name: 'SetPrivateData', nargs: 5, handler: 'IDirect3DCubeTexture9_SetPrivateData' },
    { name: 'GetPrivateData', nargs: 4, handler: 'IDirect3DCubeTexture9_GetPrivateData' },
    { name: 'FreePrivateData', nargs: 2, handler: 'IDirect3DCubeTexture9_FreePrivateData' },
    { name: 'SetPriority', nargs: 2, handler: 'IDirect3DCubeTexture9_SetPriority' },
    { name: 'GetPriority', nargs: 1, handler: 'IDirect3DCubeTexture9_GetPriority' },
    { name: 'PreLoad', nargs: 1, handler: 'IDirect3DCubeTexture9_PreLoad' },
    { name: 'GetType', nargs: 1, handler: 'IDirect3DCubeTexture9_GetType' },
    { name: 'SetLOD', nargs: 2, handler: 'IDirect3DCubeTexture9_SetLOD' },
    { name: 'GetLOD', nargs: 1, handler: 'IDirect3DCubeTexture9_GetLOD' },
    { name: 'GetLevelCount', nargs: 1, handler: 'IDirect3DCubeTexture9_GetLevelCount' },
    { name: 'GetLevelDesc', nargs: 3 },
    { name: 'GetCubeMapSurface', nargs: 4 },
    { name: 'LockRect', nargs: 6, handler: 'IDirect3DCubeTexture9_LockRect' },
    { name: 'UnlockRect', nargs: 3, handler: 'IDirect3DCubeTexture9_UnlockRect' },
    { name: 'AddDirtyRect', nargs: 3, handler: 'IDirect3DCubeTexture9_AddDirtyRect' },
  ] },
];

const vtableGlobals = [
  { prefix: 'IDirect3D8', global: 'DX_VTBL_D3D8', methods: interfaces[0].methods.map(m => m.name) },
  { prefix: 'IDirect3DDevice8', global: 'DX_VTBL_D3DDEV8', methods: interfaces[1].methods.map(m => m.name) },
];

module.exports = { interfaces, vtableGlobals };
