  ;; ============================================================
  ;; src/00-regions.wat — THE memory map, declared.
  ;;
  ;; Milestone 6 step 1 of docs/watx-migration-plan.md; designed in
  ;; docs/watx-region-safety-design.md.
  ;;
  ;; THE MAP IS ALLOCATED, NOT WRITTEN DOWN (since c409c554, wave 3). Almost
  ;; every entry is `region.declare`: it states a region's SIZE and alignment
  ;; and the compiler's allocator chooses the base. There is no base in this
  ;; file to read for those, and a tool that scans the text for one gets an
  ;; empty map with no error — ask `tools/region-layout.js`, which puts the
  ;; question to the compiler, or read the generated JS mirror.
  ;;
  ;; ONLY A HANDFUL OF REGIONS ARE PINNED. `region.declare-fixed` is the one
  ;; head in the family that does not allocate: the base is an input and the
  ;; compiler verifies it. It is spelled here only where an address is load
  ;; bearing outside this file — $GUEST_BASE, $VIRTUAL_BACKING_BASE,
  ;; $DIB_BACKING_BASE and $THREAD_RPC — plus the three `region.declare-derived`
  ;; entries that hang off $GUEST_BASE and the $DIRECT_WINDOW span. Everything
  ;; else may and does MOVE when a size changes or a region is added, so a JS
  ;; copy of an allocated base is a bug waiting for the next edit; consumers
  ;; read `lib/region-map.generated.js`, regenerated by
  ;; `tools/gen-region-map.js`.
  ;;
  ;; What the compiler now proves, on every build, in both modes:
  ;;   - no two declared regions overlap (a deliberate nesting says (within $R))
  ;;   - every base meets its declared alignment
  ;;   - no region runs past the memory that exists at instantiation
  ;;   - no region is declared twice
  ;; and, at any use site that adopts them, that a constant offset is inside its
  ;; region — (region.addr $R 0x40), which emits exactly the i32.const the raw
  ;; hex literal emits.
  ;;
  ;; DECLARATIONS EMIT NOTHING. This whole file adds zero bytes to the shipped
  ;; wasm: a declaration is compile-time-only under WATX, and the canonical
  ;; artifacts were byte-identical with and without it when the set landed
  ;; (tail 984347 B 01daf6ccfbd115e3, compat 984796 B 0ee6414668129ac4).
  ;; The `WINE_WAT_COMPILER=legacy` rollback that used to be quoted here is
  ;; RETIRED (24b79256, docs/watx-region-safety-design.md §11): declarations
  ;; alone were legacy-safe, but the region spellings the tree now uses in
  ;; expression and data position compile to `unreachable` under the legacy
  ;; path, so it is a hard error rather than a second opinion.
  ;;
  ;; RELATIONSHIP TO THE EXISTING GLOBALS. Each declaration mirrors a
  ;; `(global $NAME i32 ...)` / `(global $NAME_SIZE i32 ...)` pair, which is
  ;; still what the code reads and what tools/wat-memory-map.js and
  ;; test/test-wat-memory-map.js derive their map from.
  ;; tools/check-region-decls.js holds the two in step and fails the build on
  ;; any disagreement, so this file cannot rot into a decorative second opinion.
  ;; `(owner "file:$symbol")` names the stable source form that owns a use.
  ;;
  ;; Converting consumers to address regions by name is Milestone 6 stage B and
  ;; is UNDER WAY: wave 1 (2026-08-31) symbolized ~96 sites across src/ and
  ;; lib/, and wave 2 added the regions this map was missing entirely. So both
  ;; `$NAME` in expression position and `(data (region.addr $NAME OFF) ...)`
  ;; now appear in src/ — see docs/watx-region-safety-design.md §5 and §13.
  ;;
  ;; TO ADD A REGION: declare its $NAME/$NAME_SIZE globals where the feature
  ;; lives, as before, then add the mirror here. The build fails if you skip it
  ;; or get it wrong, which is the entire point.
  ;; ============================================================

  ;; The low string-constant pool and the MapVirtualKey byte tables. Neither
  ;; had a _SIZE global, so neither was visible to wat-memory-map.js or to any
  ;; overlap gate; 57 data segments lived here in no region at all.
  ;; The allocator starts here. Below it: NULL_SENTINEL at 0xF0, which
  ;; $g2w's sink behaviour pins and nothing may be placed on top of.
  (region.floor 0x00000100)

  (region.declare $STRING_CONSTANTS (size 0x00000280) (align 0x00000100)
    (owner "01-header.wat:$STRING_CONSTANTS"))
  (region.declare $VK_SCAN_TABLES (size 0x00000080) (align 0x00000080)
    (owner "09a7-handlers-dispatch.wat:$VK_SCAN_TABLES"))
  (region.declare $UPDATE_RECT (size 0x00001000) (align 0x00001000)
    (owner "01-header.wat:$UPDATE_RECT"))
  (region.declare $UPDATE_FLAGS (size 0x00000100) (align 0x00001000)
    (owner "01-header.wat:$UPDATE_FLAGS"))
  ;; WIDENED 0x80 -> 0x1A0 (wave 2). The declaration covered only as far as
  ;; "SysLink"; the class-name block runs to the RGB555 masks at 0x32A0, so
  ;; everything past 0x3180 -- the DirectAnimation names, SysTreeView32, the
  ;; statusbar/toolbar classes -- sat outside every region and outside every
  ;; gate. The three blocks that follow used to be undeclared data segments.
  (region.declare $CLASS_NAME_STRINGS (size 0x000001A0) (align 0x00000100)
    (owner "09a-handlers1-user.wat:$control_class_name_ptr"))
  (region.declare $DIB_DEFAULT_RGB555_MASKS (size 0x0000000C) (align 0x00000010)
    (owner "01-header.wat:$DIB_DEFAULT_RGB555_MASKS"))
  (region.declare $OLE_STRINGS (size 0x000000E0) (align 0x00000010)
    (owner "01-header.wat:$OLE_STRINGS"))
  (region.declare $ENV_DEFAULTS (size 0x000000C0) (align 0x00000010)
    (owner "01-header.wat:$ENV_DEFAULTS"))
  (region.declare $WND_BG_BRUSH_TABLE (size 0x00000400) (align 0x00000100)
    (owner "09c0-window-table.wat:$wnd_bg_brush_reset_slot"))
  (region.declare $WND_CLASS_CURSOR_TABLE (size 0x00000400) (align 0x00000100)
    (owner "09c0-window-table.wat:$wnd_class_cursor_reset_slot"))
  (region.declare $CLASS_EXTRA_TABLE (size 0x00000100) (align 0x00000100)
    (stride $CLASS_EXTRA_STRIDE (count 64))
    (owner "09c0-window-table.wat:$class_extra_addr"))
  ;; The two Win16 name tables in the hole after CLASS_EXTRA_TABLE. Both were
  ;; raw (data (i32.const ...)) segments in no region at all; each is sized to
  ;; exactly the bytes its segment emits, so growing one is a compile error.
  (region.declare $WIN16_FONT_FACES (size 0x00000030) (align 0x00000100)
    (owner "09e-win16-api.wat:$WIN16_FONT_FACES"))
  (region.declare $WIN16_MMSYSTEM_NAMES (size 0x000000F5) (align 0x00000010)
    (owner "09e-win16-api.wat:$WIN16_MMSYSTEM_NAMES"))
  (region.declare $DIALOG_STATE_TABLE (size 0x00001000) (align 0x00001000)
    (owner "09c0-window-table.wat:$dialog_state_addr"))
  ;; 256 slots x 8 bytes: the DS_SETFONT font the dialog manager created and
  ;; the base units measured from it.
  (region.declare $DIALOG_FONT_TABLE (size 0x00000800) (align 0x00000010)
    (owner "09c0-window-table.wat:$dialog_font_addr"))
  (region.declare $WINDOW_UNICODE_TABLE (size 0x00000100) (align 0x00001000)
    (owner "09c0-window-table.wat:$wnd_unicode_reset_slot"))
  (region.declare $SHARED_PROCESS_ID (size 0x00000004) (align 0x00000100)
    (owner "01-header.wat:$SHARED_PROCESS_ID"))
  (region.declare $SHARED_DLG_ENDED (size 0x00000004)
    (owner "01-header.wat:$SHARED_DLG_ENDED"))
  (region.declare $SHARED_DLG_RESULT (size 0x00000004)
    (owner "01-header.wat:$SHARED_DLG_RESULT"))
  (region.declare $SHARED_DLG_PUMP_HWND (size 0x00000004)
    (owner "01-header.wat:$SHARED_DLG_PUMP_HWND"))
  ;; Host-supplied environment overrides. The 240-byte extent is the bound
  ;; $test_launch_env_add already enforced as a bare literal; it now reads the
  ;; region's own size, so the two cannot disagree.
  (region.declare $LAUNCH_ENV_OVERRIDES (size 0x000000F0) (align 0x00000010)
    (owner "01-header.wat:$LAUNCH_ENV_OVERRIDES"))
  (region.declare $WINDOW_EXTRA_TABLE (size 0x00002800) (align 0x00000100)
    (stride $WND_EXTRA_STRIDE (count $MAX_WINDOWS))
    (owner "09c0-window-table.wat:$wnd_extra_addr"))
  (region.declare $PAINT_SCRATCH (size 0x00000100) (align 0x00000100)
    (stride 0x10 (count $PAINT_SCRATCH_SLOTS))
    (owner "10-helpers.wat:$paint_scratch_take"))
  (region.declare $WND_CLASS_SLOT_TABLE (size 0x00000100) (align 0x00000100)
    (owner "09c0-window-table.wat:$wnd_class_slot_reset_slot"))
  (region.declare $WND_RECORDS (size 0x00001800) (align 0x00001000)
    (stride 0x18 (count $MAX_WINDOWS))
    (owner "09c0-window-table.wat:$wnd_record_addr"))
  (region.declare $CONTROL_TABLE (size 0x00001000) (align 0x00000100)
    (owner "09c3-controls.wat:$ctrl_slot_addr"))
  (region.declare $CONTROL_GEOM (size 0x00000800) (align 0x00000100)
    (owner "09c3-controls.wat:$ctrl_geom_addr"))
  (region.declare $CLASS_RECORDS (size 0x00000C00) (align 0x00001000)
    (owner "09c0-window-table.wat:$class_record_addr"))
  (region.declare $TIMER_TABLE (size 0x00000140) (align 0x00000100)
    (stride $TIMER_ENTRY_SIZE (count $TIMER_MAX))
    (owner "09a-handlers.wat:$timer_set"))
  (region.declare $ACCEL_TABLES (size 0x00000400) (align 0x00000100)
    (stride $ACCEL_TABLE_STRIDE (count $ACCEL_TABLE_COUNT))
    (owner "09a5-handlers-window.wat:$accel_table_record_locked"))
  (region.declare $MENU_DATA_TABLE (size 0x00000400) (align 0x00000010)
    (owner "09c0-window-table.wat:$menu_data_reset_slot"))
  (region.declare $WND_DLG_RECORDS (size 0x00002000) (align 0x00000010)
    (owner "01-header.wat:$WND_DLG_RECORDS"))
  ;; Four dwords of cross-instance waveOut identity in the 16-byte hole
  ;; between WND_DLG_RECORDS and SCROLL_TABLE. Declared rather than spelled
  ;; (region.end $WND_DLG_RECORDS): it is its own object, and an adjacency is
  ;; not an address (docs/watx-region-safety-design.md 5.1).
  (region.declare $WAVE_OUT_SHARED (size 0x00000010) (align 0x00000010)
    (owner "01-header.wat:$WAVE_OUT_SHARED"))
  ;; AVIFileInit/AVIFileExit balance one process-wide library reference count.
  ;; It must live in shared memory because guest threads use separate WASM
  ;; instances over the same Windows process.
  (region.declare $AVIFILE_STATE (size 0x00000004) (align 0x00000004)
    (owner "01-header.wat:$AVIFILE_STATE"))
  ;; Process-wide BASS 2.x compatibility state. The first 0x80 bytes hold the
  ;; device/configuration words and sixteen per-guest-thread error slots,
  ;; followed by 64 Sample records and 128 Channel records. Sample PCM itself
  ;; remains heap-owned so BASS_SampleFree can release the copied VFS image.
  (region.declare $BASS_STATE (size 0x00001900) (align 0x00000100)
    (owner "09a3-handlers-audio.wat:$bass_sample_addr"))
  (region.declare $SCROLL_TABLE (size 0x00001800) (align 0x00000010)
    (owner "09c0-window-table.wat:$scroll_record_addr"))
  (region.declare $FLASH_TABLE (size 0x00000100) (align 0x00000010)
    (owner "09a5-handlers-window.wat:$handle_FlashWindow"))
  (region.declare $NC_FLAGS (size 0x00000400) (align 0x00000010)
    (owner "10-helpers.wat:$nc_flags_set"))
  (region.declare $TITLE_TABLE (size 0x00000800) (align 0x00000010)
    (owner "01-header.wat:$TITLE_TABLE"))
  (region.declare $CLIENT_RECT (size 0x00001000) (align 0x00000010)
    (owner "01-header.wat:$CLIENT_RECT"))
  (region.declare $SHOW_STATE_TABLE (size 0x00000100) (align 0x00000010)
    (owner "09c4-defwndproc.wat:$wnd_show_state_addr"))
  (region.declare $WINDOW_REGION_BITS (size 0x00000020) (align 0x00000010)
    (owner "01-header.wat:$WINDOW_REGION_BITS"))
  (region.declare $NATIVE_STATUS_BITS (size 0x00000020) (align 0x00000010)
    (owner "09c3-controls.wat:$statusbar_native_mark_slot"))
  (region.declare $NATIVE_TAB_BITS (size 0x00000020) (align 0x00000010)
    (owner "09c3-controls.wat:$tab_native_mark_slot"))
  (region.declare $SHARED_MODAL_DLG_HWND (size 0x00000004) (align 0x00000010)
    (owner "01-header.wat:$SHARED_MODAL_DLG_HWND"))
  (region.declare $SHARED_MODAL_RESULT (size 0x00000004)
    (owner "01-header.wat:$SHARED_MODAL_RESULT"))
  (region.declare $SHARED_MODAL_DONE (size 0x00000004)
    (owner "01-header.wat:$SHARED_MODAL_DONE"))
  (region.declare $CS_RING (size 0x00000100) (align 0x00000100)
    (stride 0x4 (count 64)) (mask $CS_MASK) (size-is-power-of-2)
    (owner "05-alu.wat:$cs_push"))
  ;; timeSetEvent slots: 8 x 24 bytes, then the id allocator in its own region.
  ;; Sized from $MM_TIMER_MAX x $MM_TIMER_ENTRY, so growing either without
  ;; growing this is a compile error rather than a silent overrun into whatever
  ;; the allocator packed next.
  (region.declare $MM_TIMER_TABLE (size 0x000000C0) (align 0x00000010)
    (stride $MM_TIMER_ENTRY (count 8))
    (owner "09a-handlers.wat:$mm_timer_slot"))
  (region.declare $MM_TIMER_NEXT_ID (size 0x00000004)
    (owner "01-header.wat:$MM_TIMER_NEXT_ID"))
  (region.declare $MCI_DEVICE_TABLE (size 0x00000100) (align 0x00000100)
    (owner "09a3-handlers-audio.wat:$mci_slot_addr"))
  ;; Open HMMIO state: 8 x 32-byte slots. Shared memory rather than a lazily
  ;; heap-allocated per-instance table, because one guest thread opens a
  ;; handle and another advances it -- SimGolf's sound.dll does exactly that.
  (region.declare $MMIO_BUF_TABLE (size 0x00000100) (align 0x00000010)
    (owner "09a3-handlers-audio.wat:$mmio_slot_addr"))
  (region.declare $OWNER_TABLE (size 0x00000400) (align 0x00000100)
    (owner "09c0-window-table.wat:$wnd_owner_reset_slot"))
  ;; The system colours a program changed with SetSysColors, as 32 pairs of
  ;; {was it set, COLORREF}. Only the pairs a guest actually wrote live here;
  ;; every other index still answers from the stock Win98 palette, so the
  ;; table is an override and not a copy that could drift from it.
  (region.declare $USER_SYS_COLORS (size 0x00000100) (align 0x00000100)
    (owner "10-helpers.wat:$win98_sys_color_slot"))
  ;; DISPDIB's emulated display state (mode, palette-present, running) and the
  ;; three literals its surface is recognized by. The driver is a window
  ;; class, not an export table, so both live here rather than in a DLL image.
  (region.declare $DISPDIB_STATE (size 0x00000040) (align 0x00000040)
    (owner "09d5-dispdib.wat:$dispdib_wndproc"))
  (region.declare $DISPDIB_STRINGS (size 0x00000060) (align 0x00000040)
    (owner "09d5-dispdib.wat:$dispdib_is_class_name"))
  ;; The reserved page just below GUEST_BASE. Four undeclared string blocks
  ;; interleaved with the declared tables that already lived here; each is
  ;; bounded by the next declared region, so the extents are not guesses.
  (region.declare $USER_DIALOG_STRINGS (size 0x00000270) (align 0x00001000)
    (owner "01-header.wat:$USER_DIALOG_STRINGS"))
  (region.declare $BROWSE_DIALOG_STRINGS (size 0x00000060) (align 0x00000010)
    (owner "01-header.wat:$BROWSE_DIALOG_STRINGS"))
  (region.declare $DX_VERSION_INFO (size 0x0000005C) (align 0x00000010)
    (owner "09a1-comctl-handlers.wat:$handle_GetFileVersionInfoA"))
  ;; Storage for every string the compiler interns from a `"text"` literal.
  ;; Named by `(string.pool $WATX_STRING_POOL)` in 01-header.wat; without that
  ;; declaration the pool is placed above the last data segment, which in this
  ;; map is the middle of $D3DIM_AUX. Nothing hand-places bytes in here and no
  ;; offset into it is ever written down — that is the entire point. Growing it
  ;; is a one-line edit and the compiler says exactly how many bytes short it is.
  (region.declare $WATX_STRING_POOL (size 0x00001600) (align 0x00000010)
    (owner "01-header.wat:$WATX_STRING_POOL"))
  (region.declare $DI_DIK_VK_TABLE (size 0x00000100) (align 0x00000100)
    (owner "09a8-handlers-directx.wat:$DI_DIK_VK_TABLE"))
  (region.declare $RICHEDIT_FORMAT_TABLE (size 0x00000400) (align 0x00000010)
    (owner "01-header.wat:$RICHEDIT_FORMAT_TABLE"))
  (region.declare $RICHEDIT_PARA_TABLE (size 0x00000400) (align 0x00000010)
    (owner "01-header.wat:$RICHEDIT_PARA_TABLE"))
  (region.declare $RESERVED_PAGE_STRINGS (size 0x00000300) (align 0x00000080)
    (owner "01-header.wat:$RESERVED_PAGE_STRINGS"))
  ;; The texts on the shutting-down / safe-to-turn-off screens.
  (region.declare $POWER_SCREEN_STRINGS (size 0x000000C0) (align 0x00000010)
    (owner "09c3-controls4-shell-dialogs.wat:$POWER_SCREEN_STRINGS"))
  (region.declare-fixed $GUEST_BASE (base 0x00012000) (size 0x03C00000) (align 0x00001000)
    (owner "01-header.wat:$GUEST_BASE"))
  ;; Per-owner USER activation history fits in the remaining aligned table gap
  ;; before the fixed guest mirror. Keep the address allocator-owned rather
  ;; than pinning another raw address.
  (region.declare $LAST_ACTIVE_POPUP_TABLE (size 0x00000400) (align 0x00000100)
    (owner "09a1-comctl-handlers.wat:$wnd_last_active_popup_addr_for_slot"))
  ;; WIDENED 0x100000 -> 0x3EE000 (wave 3). The low heap never fitted in 1MB:
  ;; $heap_low_reserve hands out 1MB chunks and stopped only when the next
  ;; chunk would reach $PAGE_INDEX_ARENA, which the hand-placed map happened to
  ;; put 4MB further up. The room a table grows into belongs in its own (size),
  ;; where a bound is checked, not in an anonymous hole beside it — reclaiming
  ;; that hole moved the page indexes down to 0x03E12000 and left the heap with
  ;; one chunk, which is a broken emulator, not a broken declaration.
  (region.declare-derived $GUEST_HEAP_BASE (base (g2w 0x04100000)) (size 0x003EE000) (align 0x00001000)
    (owner "01-header.wat:$GUEST_HEAP_BASE"))
  (region.declare $HANDLER_PAIR_HIST_COUNTS (size 0x00100000) (align 0x00001000)
    (owner "04-cache.wat:$handler_hist_record"))
  ;; Split like $THREAD_CACHE_BASE below, and for the same reason: the main
  ;; thread compiles nearly every page an app ever runs, and a worker compiles
  ;; the one routine it was spawned for. So the main thread keeps its full 128
  ;; index slots (0x100000) and each of the fifteen workers gets 16 (0x20000).
  ;; No uniform (stride ...) can describe that, and stating a false one would
  ;; be worse than stating none: 0x120000 + 15 * 0x24000 = 0x33C000, and the
  ;; region SHRINKS by 5MB while carrying twice as many threads.
  ;;
  ;; WIDENED 0x2E0000 -> 0x33C000 (block executor round 13). A slot is no
  ;; longer 4096 u16 index entries alone: it carries two 512-byte bitmaps over
  ;; the page's 16KB chunk, one bit per 4-byte threaded word, marking op starts
  ;; and block ends. That is what makes the published threaded stream
  ;; self-describing, so the region walker can classify a block that is ALREADY
  ;; compiled instead of decoding it again -- see docs/block-executor-design.md
  ;; section 22. Slot count is unchanged (MAIN_BYTES / PAGE_INDEX_BYTES), so
  ;; this buys nothing and costs nothing beyond the 0x5C000 of extra map.
  ;;
  ;; WIDENED 0x33C000 -> 0x69C000 (2026-09-28): the main thread's slots went
  ;; 128 -> 512 (0x120000 -> 0x480000; 0x480000 + 15 * 0x24000 = 0x69C000).
  ;; Warcraft III gameplay executes ~450 distinct code pages, so 128 slots made
  ;; $page_index_alloc evict a live page on nearly every page miss and the
  ;; game re-decoded ~470 blocks a batch. docs/re-notes/warcraft3-demo.md,
  ;; "Decode storms".
  (region.declare $PAGE_INDEX_ARENA (size 0x0069C000) (align 0x00001000)
    (owner "01-header.wat:$PAGE_INDEX_ARENA"))
  ;; Same split: main 4096 directory entries, each worker 256. A slot is 32
  ;; bytes since block-executor round 14 (docs/block-executor-design.md section
  ;; 23) -- a page now owns TWO chunks, the threaded one and a second one for
  ;; executor descriptors, and each needs a base and a used|class word. So
  ;; main is 0x20000, a worker 0x2000, and 0x20000 + 15 * 0x2000 = 0x3E000.
  ;; Main was 1024 entries until 2026-09-28: direct-mapped on page number, so
  ;; pages 4MB apart shared a slot, and W3's Game.dll/Storm/msvcrt code aliased
  ;; into 585K evictions over its route. 4096 entries (16MB of page numbers)
  ;; took that to 80.
  (region.declare $PAGE_DIR_BASE (size 0x0003E000) (align 0x00001000)
    (owner "01-header.wat:$PAGE_DIR_BASE"))
  (region.declare $WIN16_APP_DLL_STAGING (size 0x00600000) (align 0x00001000)
    (stride $WIN16_APP_DLL_STRIDE (count 6))
    (owner "08c-ne-loader.wat:$win16_dll_staging"))
  ;; NOT eight equal partitions any more, and deliberately not sixteen equal
  ;; ones either. The main thread is not one thread among many: it decodes the
  ;; whole program, and a worker decodes the one routine it was spawned for.
  ;; Sixteen equal shares of this region would have cut main from 3.9MB to
  ;; 1.9MB to buy workers a partition each they cannot begin to fill.
  ;;
  ;; So: main takes 0x00EFE000 (15MB, nearly four times what it had) and each
  ;; of fifteen workers takes $THREAD_CACHE_STRIDE = 0x000C0000. That is
  ;; 0xEFE000 + 15 * 0xC0000 = 0x1A3E000. Main gave up two pages on 2026-09-28
  ;; to pay for $XMM_FILE: the map was at its ceiling (a shake could not
  ;; place it), and 8KB of a 15MB block cache is not measurable. Workers had 0x100000 each until the
  ;; micro-op tier needed an arena per worker: the 0x40000 each gave up is
  ;; $UOP_THREAD_ARENAS below, so the map as a whole did not grow.
  ;; $init_thread in 13-exports.wat is the one place that knows the shape.
  ;;
  ;; Why fifteen workers: Warcraft III keeps five threads alive and then asks
  ;; for a burst of five more at once. At seven worker slots the eighth
  ;; CreateThread was refused for want of a partition, MSVCRT _beginthreadex
  ;; returned 0, the exe abandoned the worker pool it was building at
  ;; 0x413c10, its subsystem init rolled back, and the refcounted object the
  ;; campaign briefing calls through was freed while still in use.
  ;; docs/re-notes/warcraft3-demo.md has the whole measured chain.
  ;;
  ;; PINNED 2026-10-10 in a tail carved from the sparse backing pool, like
  ;; $GUEST_PAGE_TABLE, to make room in the direct window for the three
  ;; fixed guest pools below ($GUEST_FIXED_POOL_*). Out here the guest cannot
  ;; reach decoded code through a stray direct-window pointer either.
  (region.declare-fixed $THREAD_CACHE_BASE (base 0x1A000000) (size 0x01A3E000) (align 0x00001000)
    (owner "01-header.wat:$THREAD_CACHE_BASE"))
  ;; The eight x86 GPRs, per guest thread. Memory is SHARED between instances
  ;; while wasm globals are per-instance, so one fixed address would give every
  ;; worker the same register file — hence a tid-strided partition, exactly
  ;; like $THREAD_CACHE_BASE above. The stride is a full 64-byte cache line so
  ;; two threads never share one, and 64 bytes is 16 slots for 8 registers, so
  ;; a 4-bit-masked index that goes out of range lands in this thread's own
  ;; padding rather than another thread's file.
  (region.declare $REGFILE (size 0x00000400) (align 0x00000040)
    (stride 0x40 (count $REGFILE_THREADS))
    (owner "01-header.wat:$REGFILE"))
  ;; toyvm-style micro-op engine arena (src/07d-uop-engine.wat, see
  ;; docs/uop-tier-design.md): program words, temp vregs and window slots.
  ;; The MAIN thread's. A program names its instance's $reg_base and temps,
  ;; so each guest thread (its own instance over this shared memory) needs an
  ;; arena of its own; workers take the tid-strided one below.
  (region.declare $UOP_ARENA (size 0x00100000) (align 0x00001000)
    (owner "07d-uop-engine.wat:$UOP_ARENA"))
  ;; Worker N (1..15) gets 0x40000 at (N-1)*0x40000 -- the same split as
  ;; $THREAD_CACHE_BASE, and paid for by it (see there): a worker runs the one
  ;; routine it was spawned for, so a quarter of the main arena is plenty.
  (region.declare $UOP_THREAD_ARENAS (size 0x003C0000) (align 0x00001000)
    (stride 0x40000 (count 15))
    (owner "07d-uop-engine.wat:$UOP_THREAD_ARENAS"))
  ;; The x86 -> micro-op compiler's working memory (07e-uop-compiler.wat):
  ;; decoded instructions, blocks, flow states, the op stream and its maps.
  ;; Nothing in it outlives one compile.
  (region.declare $UOP_CSCRATCH (size 0x0013A000) (align 0x00001000)
    (owner "07e-uop-compiler.wat:$UOP_CSCRATCH"))
  ;; The eight x87 physical registers, per guest thread, for the same reason:
  ;; +0..+63 the f64 values, +64..+127 the exact-integer i64 shadows (FILD
  ;; m64 / FISTP m64). Indexed by physical register, so ST(i) is one load at
  ;; ((top+i)&7)*8 instead of an eight-way branch over globals.
  (region.declare $FPU_FILE (size 0x00000800) (align 0x00000040)
    (stride 0x80 (count $REGFILE_THREADS))
    (owner "01-header.wat:$FPU_FILE"))
  ;; The eight SSE registers, per guest thread: XMMn at +n*16, so reading one
  ;; is a single v128.load instead of an eight-way branch over i64 globals.
  (region.declare $XMM_FILE (size 0x00000800) (align 0x00000040)
    (stride 0x80 (count $REGFILE_THREADS))
    (owner "01-header.wat:$XMM_FILE"))
  (region.declare-derived $GUEST_STACK (base (g2w 0x07400000)) (size 0x00100000) (align 0x00001000)
    (owner "01-header.wat:$GUEST_STACK"))
  (region.declare-derived $THUNK_BASE (base (g2w 0x07500000)) (size 0x00040000) (align 0x00001000)
    (owner "08-pe-loader.wat:$load_pe"))
  ;; Guest memory a program may reserve at a FIXED address past its image
  ;; window. The direct window translates every guest address up to
  ;; 0x08000000 + image_base - GUEST_BASE, so without a hole here such an
  ;; address lands on emulator tables. Crusaders of Might and Magic reserves
  ;; exactly these three: its level files are memory images whose pointers are
  ;; already relocated to 0x04000000, 0x06000000 and 0x08000000
  ;; (docs/re-notes/crusaders-mm-demo.md), so the pools must be those
  ;; addresses, not merely somewhere. VirtualAlloc hands them out only to a
  ;; fixed MEM_RESERVE inside one of them ($guest_fixed_pool_of).
  (region.declare-derived $GUEST_FIXED_POOL_A (base (g2w 0x04000000)) (size 0x00080000) (align 0x00001000)
    (owner "09a0-handlers-base.wat:$guest_fixed_pool_of"))
  (region.declare-derived $GUEST_FIXED_POOL_B (base (g2w 0x06000000)) (size 0x00EE1000) (align 0x00001000)
    (owner "09a0-handlers-base.wat:$guest_fixed_pool_of"))
  (region.declare-derived $GUEST_FIXED_POOL_C (base (g2w 0x08000000)) (size 0x00100000) (align 0x00001000)
    (owner "09a0-handlers-base.wat:$guest_fixed_pool_of"))
  ;; ...and a fourth, committed at once: 0x29040 bytes at 0x05000000 (0x450fc0).
  (region.declare-derived $GUEST_FIXED_POOL_D (base (g2w 0x05000000)) (size 0x0002A000) (align 0x00001000)
    (owner "09a0-handlers-base.wat:$guest_fixed_pool_of"))
  (region.declare $PE_STAGING (size 0x00800000) (align 0x00001000)
    (owner "08-pe-loader.wat:$load_pe"))
  (region.declare $DLL_TABLE (size 0x00000800) (align 0x00001000)
    (stride 0x20 (count $DLL_TABLE_CAPACITY))
    (owner "08b-dll-loader.wat:$load_dll"))
  (region.declare $DLL_RSRC_TABLE (size 0x00000200) (align 0x00000100)
    (stride 0x8 (count $DLL_TABLE_CAPACITY))
    (owner "01-header.wat:$DLL_RSRC_TABLE"))
  (region.declare $DLL_PATH_TABLE (size 0x00000100) (align 0x00000100)
    (stride 0x4 (count $DLL_TABLE_CAPACITY))
    (owner "01-header.wat:$DLL_PATH_TABLE"))
  (region.declare $DLL_FLAGS_TABLE (size 0x00000100) (align 0x00000100)
    (stride 0x4 (count $DLL_TABLE_CAPACITY))
    (owner "08b-dll-loader.wat:$load_dll"))
  (region.declare $GDI_BITMAP_TEXT_LAYOUT (size 0x00021000) (align 0x00001000)
    (owner "10b-gdi-font.wat:$GDI_BITMAP_TEXT_LAYOUT"))
  (region.declare $GDI_BITMAP_TEXT_PREFIX (size 0x00011000) (align 0x00001000)
    (owner "10b-gdi-font.wat:$GDI_BITMAP_TEXT_PREFIX"))
  (region.declare $WND_Z_ORDER_TABLE (size 0x00000400) (align 0x00001000)
    (owner "09c0-window-table.wat:$wnd_z_addr_for_slot"))
  (region.declare $WND_CLASS_ICON_TABLE (size 0x00000400) (align 0x00001000)
    (owner "09c0-window-table.wat:$wnd_class_icon_reset_slot"))
  (region.declare $WIN16_FILE_TABLE (size 0x00000400) (align 0x00000100)
    (stride 0x4 (count $WIN16_FILE_MAX))
    (owner "01-header.wat:$WIN16_FILE_TABLE"))
  (region.declare $WND_OWN_DC_TABLE (size 0x00000400) (align 0x00000100)
    (owner "09c0-window-table.wat:$wnd_own_dc_addr_for_slot"))
  (region.declare $WND_HINSTANCE_TABLE (size 0x00000400) (align 0x00000100)
    (owner "09c0-window-table.wat:$wnd_hinstance_reset_slot"))
  (region.declare $WIN16_BUILTIN_NAMES (size 0x00000280) (align 0x00001000)
    (owner "09e-win16-api.wat:$WIN16_BUILTIN_NAMES"))
  (region.declare $WND_THREAD_TABLE (size 0x00000400) (align 0x00000100)
    (owner "09c0-window-table.wat:$wnd_thread_addr"))
  (region.declare $THREAD_MSG_INPUT_FLAGS (size 0x00001000) (align 0x00000100)
    (owner "09a-handlers.wat:$thread_msg_input_flags_addr"))
  (region.declare $THREAD_MSG_QUEUES (size 0x00002080) (align 0x00000100)
    (stride $THREAD_MSG_QUEUE_STRIDE (count 8))
    (owner "09a-handlers.wat:$thread_msg_queue_addr"))
  ;; $gdi_nearest_cache_slot hashes a colour and masks with SLOTS-1, so the
  ;; slot count being a power of two is what makes the mask a bound.
  (region.declare $GDI_NEAREST_CACHE (size 0x00008000) (align 0x00001000)
    (stride 0x8 (count $GDI_NEAREST_CACHE_SLOTS)) (size-is-power-of-2)
    (owner "10g-gdi-raster.wat:$GDI_NEAREST_CACHE"))
  (region.declare $WIN16_THUNK_TABLE (size 0x00002000) (align 0x00001000)
    (stride 0x4 (count $WIN16_THUNK_MAX))
    (owner "08c-ne-loader.wat:$win16_thunk_for"))
  (region.declare $WIN16_SEG_TABLE (size 0x00020000) (align 0x00001000)
    (owner "08c-ne-loader.wat:$win16_seg_base"))
  ;; 8 bytes per API (hash, id); 0x8000 filled up at 4096 APIs (2026-10-06).
  (region.declare $API_HASH_TABLE (size 0x00010000) (align 0x00001000)
    (owner "10-helpers.wat:$lookup_api_id"))
  (region.declare $TEXT_SCRATCH (size 0x00000400) (align 0x00001000)
    (owner "01-header.wat:$TEXT_SCRATCH"))
  (region.declare $CONSOLE_TEXT (size 0x00003000) (align 0x00001000)
    (stride 0x2 (count $CONSOLE_MAX_CELLS))
    (owner "09a2-handlers-console.wat:$console_buffers_init"))
  (region.declare $CONSOLE_ATTR (size 0x00003000) (align 0x00001000)
    (stride 0x2 (count $CONSOLE_MAX_CELLS))
    (owner "09a2-handlers-console.wat:$console_buffers_init"))
  (region.declare $CONSOLE_INPUT (size 0x00001000) (align 0x00001000)
    (owner "09a2-handlers-console.wat:$console_input_count"))
  (region.declare $PAGE_WATCH_ROOT (size 0x00001000) (align 0x00001000)
    (owner "03a-page-watch.wat:$page_watch_acquire"))
  (region.declare $DIB_PAGE_USED (size 0x00004000) (align 0x00001000)
    (owner "10-helpers.wat:$dib_alloc"))
  (region.declare $DIB_PAGE_RUNS (size 0x00008000) (align 0x00001000)
    (owner "10-helpers.wat:$dib_alloc"))
  (region.declare $GDI_REGION_BANDS (size 0x000D0000) (align 0x00001000)
    (owner "10d-gdi-region-path.wat:$gdi_rgn_bands"))
  (region.declare $GDI_REGION_WORK (size 0x00003400) (align 0x00001000)
    (owner "10d-gdi-region-path.wat:$gdi_rgn_alloc_ellipse"))
  (region.declare $GDI_DC_CLIP_TABLE (size 0x00000800) (align 0x00001000)
    (stride 0x8 (count $GDI_DC_CLIP_COUNT))
    (owner "10d-gdi-region-path.wat:$gdi_dc_clip_entry"))
  (region.declare $GDI_DC_SAVE_TABLE (size 0x00000800) (align 0x00000100)
    (stride 0x8 (count $GDI_DC_SAVE_COUNT))
    (owner "10e-gdi-metafile.wat:$gdi_dc_meta_entry"))
  (region.declare $GDI_LINE_DESC (size 0x00000050) (align 0x00001000)
    (owner "10g-gdi-raster.wat:$gdi_line_can_raster"))
  (region.declare $GDI_BLIT_DESC (size 0x000000A0) (align 0x00000100)
    (owner "01-header.wat:$GDI_BLIT_DESC"))
  (region.declare $GDI_BITMAP_PLAN (size 0x00000030) (align 0x00000010)
    (owner "10a-gdi-bitmap.wat:$gdi_bitmap_create_bitmap"))
  (region.declare $GDI_BITMAP_NAME (size 0x00000100) (align 0x00000010)
    (owner "10a-gdi-bitmap.wat:$gdi_bitmap_resource_name"))
  ;; 124-byte BITMAPV5HEADER + 256 RGBQUADs, rounded up.
  (region.declare $GDI_BITMAP_INFO_SCRATCH (size 0x00000480) (align 0x00000010)
    (owner "10a-gdi-bitmap.wat:$gdi_bitmap_info_wa"))
  ;; A LIFO arena for gathering a guest struct that straddles two sparse pages
  ;; whose backing is not adjacent. Sized for several of the largest spans any
  ;; one handler gathers (a 1028-byte LOGPALETTE or 1024-byte color table).
  (region.declare $GUEST_SPAN_SCRATCH (size 0x00004000) (align 0x00000010)
    (owner "10-helpers.wat:$guest_span_in"))
  (region.declare $WINDOW_RECT_SCRATCH (size 0x00000010) (align 0x00000010)
    (owner "01-header.wat:$WINDOW_RECT_SCRATCH"))
  (region.declare $GDI_BRUSH_DESC (size 0x00000050) (align 0x00000010)
    (owner "10g-gdi-raster.wat:$gdi_brush_sample"))
  ;; One scanline period of a patterned brush: 64 colours, which is the widest
  ;; pattern $gdi_brush_x_period will claim. A brush repeats along x, so a row
  ;; needs this many samples however wide the span is.
  (region.declare $GDI_BRUSH_ROW (size 0x00000100) (align 0x00000010)
    (owner "10g-gdi-raster.wat:$gdi_brush_fill_span"))
  ;; One counter per reason $gdi_raster_bitblt_fast32 hands a blit back to the
  ;; generic per-pixel path. A decline is not a small cost -- the generic loop
  ;; re-resolves the clip and the DC state for every pixel of the blit -- so
  ;; which reason fires is the work list for widening the fast path, and it is
  ;; the only thing that tells "this app never takes the fast blit" apart from
  ;; "it takes it and that is not where the time goes".
  (region.declare $GDI_BITBLT_DECLINE (size 0x00000040) (align 0x00000010)
    (owner "10g-gdi-raster.wat:$gdi_bitblt_decline"))
  (region.declare $GDI_PALETTE_RESOLVE (size 0x00000400) (align 0x00000010)
    (owner "01-header.wat:$GDI_PALETTE_RESOLVE"))
  (region.declare $GDI_OBJECT_GEN (size 0x00000004) (align 0x00000010)
    (owner "10d-gdi-region-path.wat:$gdi_object_record"))
  (region.declare $GDI_WINDOW_SURFACE_HWM (size 0x00000004)
    (owner "10f-gdi-dc.wat:$gdi_window_surface_record"))
  (region.declare $GDI_DC_STATE_TABLE (size 0x0000C000) (align 0x00000100)
    (stride $GDI_DC_STATE_STRIDE (count $GDI_DC_STATE_COUNT))
    (owner "10f-gdi-dc.wat:$gdi_dc_state_entry"))
  (region.declare $GDI_OBJECT_TABLE (size 0x00006000) (align 0x00000100)
    (stride $GDI_OBJECT_STRIDE (count $GDI_OBJECT_COUNT))
    (owner "10d-gdi-region-path.wat:$gdi_object_record"))
  (region.declare $GDI_WINDOW_SURFACE_TABLE (size 0x00002000) (align 0x00000100)
    (stride $GDI_WINDOW_SURFACE_STRIDE (count $GDI_WINDOW_SURFACE_COUNT))
    (owner "10f-gdi-dc.wat:$gdi_window_surface_record"))
  (region.declare $GDI_DC_AUX_TABLE (size 0x00002000) (align 0x00000100)
    (stride $GDI_DC_AUX_STRIDE (count $GDI_DC_AUX_COUNT))
    (owner "10f-gdi-dc.wat:$gdi_dc_aux_entry"))
  (region.declare $GDI_COLOR_ADJUST_TABLE (size 0x00001800) (align 0x00000100)
    (owner "10f-gdi-dc.wat:$gdi_color_adjustment_entry"))
  (region.declare $PROP_TABLE (size 0x00000C00) (align 0x00000100)
    (owner "09a7-handlers-dispatch.wat:$prop_find"))
  (region.declare $PAINT_FLAGS (size 0x00000100) (align 0x00001000)
    (owner "01-header.wat:$PAINT_FLAGS"))
  ;; Process-wide USER window-update lock. Separate WASM instances execute
  ;; guest threads, so a mutable module global would let two threads lock two
  ;; different windows at once. +0 is the locked HWND (0=free, -1=unlock in
  ;; progress); +4 is the damage-record guard; +8 is bbox-valid; +12..+24 are
  ;; the attempted-drawing left/top/right/bottom in locked-client coordinates.
  (region.declare $WINDOW_UPDATE_LOCK (size 0x00000020) (align 0x00000010)
    (owner "10-helpers.wat:$window_update_lock_covers"))
  ;; Running counts of pending paint / non-client work, so an empty
  ;; PeekMessage answers "anything to paint?" without walking 256 slots.
  ;; +0 is the number of PAINT_FLAGS bytes that are non-zero; +4/+8/+12/+16
  ;; are the number of NC_FLAGS words with bit 0/1/2/3 set. Shared memory,
  ;; not globals: every guest thread is its own instance and writes the same
  ;; tables. Only $paint_flag_store and $nc_flags_xchg write the tables, and
  ;; they keep these exact; $paint_work_audit recomputes them by scan.
  (region.declare $PAINT_WORK_COUNTS (size 0x00000020) (align 0x00000010)
    (owner "10-helpers.wat:$paint_flag_store"))
  (region.declare $TAB_NATIVE_STATE_TABLE (size 0x00000100) (align 0x00000100)
    (owner "09c3-controls.wat:$tab_native_state_get"))
  (region.declare $ICON_TABLE (size 0x00000100) (align 0x00000100)
    (owner "09a4b-handlers-cursor-icon.wat:$icon_intern"))
  (region.declare $CURSOR_TABLE (size 0x00000300) (align 0x00000100)
    (stride $CURSOR_TABLE_STRIDE (count 32))
    (owner "09a4b-handlers-cursor-icon.wat:$cursor_record"))
  (region.declare $CURSOR_MASK_DESC (size 0x00000050) (align 0x00000100)
    (owner "09a4b-handlers-cursor-icon.wat:$cursor_scale_bitmap"))
  (region.declare $CURSOR_COLOR_DESC (size 0x00000050) (align 0x00000010)
    (owner "09a4b-handlers-cursor-icon.wat:$cursor_scale_bitmap"))
  (region.declare $EDIT_LAYOUT_SCRATCH (size 0x00000C00) (align 0x00000100)
    (owner "09c3-wndprocs5-edit.wat:$edit_layout_len"))
  (region.declare $VIRTUAL_MAP_STATE (size 0x00000020) (align 0x00000100)
    (owner "10-helpers.wat:$virtual_map_commit_locked"))
  (region.declare $VIRTUAL_MAP_TABLE (size 0x00020000) (align 0x00000010)
    (owner "10-helpers.wat:$virtual_map_commit_locked"))
  ;; Ranges handed out by guest_map_alloc, i.e. MapViewOfFile views. Slot 0 is
  ;; the live count; slots 1.. are {guest base, size}. A view is not a
  ;; VirtualAlloc reservation, and VirtualFree refuses to touch one -- see
  ;; $mapped_view_contains for the app that proved this matters.
  (region.declare $MAPPED_VIEW_TABLE (size 0x000007F8) (align 0x00000010)
    (stride 8 (count $MAX_MAPPED_VIEWS))
    (owner "09a0-handlers-base.wat:$mapped_view_register"))
  (region.declare $VIRTUAL_RESERVE_TABLE (size 0x00010000) (align 0x00000010)
    (stride 8 (count $MAX_VIRTUAL_RESERVES))
    (owner "10-helpers.wat:$virtual_reserve_record"))
  (region.declare $VIRTUAL_HOLE_TABLE (size 0x00008000) (align 0x00000010)
    (stride 8 (count $MAX_VIRTUAL_HOLES))
    (owner "10-helpers.wat:$virtual_hole_add"))
  (region.declare $GDI_BITMAP_FONT_IO (size 0x00000004) (align 0x00000010)
    (owner "10b-gdi-font.wat:$GDI_BITMAP_FONT_IO"))
  (region.declare $GDI_BITMAP_FONT_DESC (size 0x00000050) (align 0x00000010)
    (owner "10b-gdi-font.wat:$GDI_BITMAP_FONT_DESC"))
  (region.declare $GDI_BITMAP_FONT_STATIC (size 0x00000170) (align 0x00000010)
    (owner "10b-gdi-font.wat:$gdi_bitmap_font_face_matches"))
  (region.declare $GDI_BITMAP_FONT_LRU (size 0x000000C0) (align 0x00000100)
    (owner "10b-gdi-font.wat:$GDI_BITMAP_FONT_LRU"))
  (region.declare $GDI_BITMAP_FONT_TABLE (size 0x00000C00) (align 0x00000100)
    (stride $GDI_BITMAP_FONT_STRIDE (count $GDI_BITMAP_FONT_COUNT))
    (owner "10b-gdi-font.wat:$GDI_BITMAP_FONT_TABLE"))
  (region.declare $TT_SUBST_TABLE (size 0x00000800) (align 0x00000100)
    (owner "10c-truetype.wat:$TT_SUBST_TABLE"))
  (region.declare $TT_SUBST_ALIAS_TABLE (size 0x00000300) (align 0x00000100)
    (owner "10c-truetype.wat:$TT_SUBST_ALIAS_TABLE"))
  (region.declare $TT_FONT_STRING_STORAGE (size 0x00000100) (align 0x00000100)
    (owner "01-header.wat:$TT_FONT_STRING_STORAGE"))
  (region.declare $GDI_DC_SYSTEM_CLIP_TABLE (size 0x00000800) (align 0x00001000)
    (stride 0x8 (count $GDI_DC_SYSTEM_CLIP_COUNT))
    (owner "10d-gdi-region-path.wat:$gdi_dc_system_clip_entry"))
  (region.declare $HEAP_SHARED (size 0x00000040) (align 0x00000100)
    (owner "01-header.wat:$HEAP_SHARED"))
  (region.declare $LOCK_TABLE (size 0x00000200) (align 0x00000010)
    (owner "01-header.wat:$LOCK_TABLE"))
  (region.declare $CS_TABLE (size 0x00000400) (align 0x00000010)
    (stride 0x4 (count $CS_TABLE_ENTRIES))
    (owner "09a-handlers3-sync.wat:$cs_slot"))
  (region.declare $SHARED_COUNTERS (size 0x00000030) (align 0x00000010)
    (owner "01-header.wat:$SHARED_COUNTERS"))
  (region.declare $CLIPBOARD_SEQUENCE (size 0x00000004) (align 0x00000004)
    (owner "01-header.wat:$CLIPBOARD_SEQUENCE"))
  (region.declare $GDI_TABLE_MARKS (size 0x00000010) (align 0x00000010)
    (owner "10d-gdi-region-path.wat:$gdi_table_mark_bump"))
  (region.declare $TV_SLOT_MARK (size 0x00000004) (align 0x00000010)
    (owner "09c2-treeview.wat:$tv_slot_limit"))
  (region.declare $TV_HANDLE_SEQ (size 0x00000004)
    (owner "01-header.wat:$TV_HANDLE_SEQ"))
  (region.declare $DX_PROCESS_STATE (size 0x00000020) (align 0x00000010)
    (owner "09a8-handlers-directx.wat:$dx_display_w_get"))
  (region.declare $LOOP_PROCESS_STATE (size 0x00000004) (align 0x00000010)
    (owner "07b-loop-match.wat:$LOOP_PROCESS_STATE"))
  (region.declare $TV_VIEW_TABLE (size 0x00000100) (align 0x00000100)
    (stride 0x10 (count $TV_VIEW_COUNT))
    (owner "09c2-treeview.wat:$tv_view_rec"))
  (region.declare $GDI_REGION_TABLE (size 0x00002000) (align 0x00001000)
    (owner "10d-gdi-region-path.wat:$gdi_rgn_alloc_rect"))
  (region.declare $GDI_DC_PATH_TABLE (size 0x00001000) (align 0x00001000)
    (stride $GDI_DC_PATH_STRIDE (count $GDI_DC_PATH_COUNT))
    (owner "10d-gdi-region-path.wat:$gdi_dc_path_entry"))
  (region.declare $HANDLER_HIST_COUNTS (size 0x00001000) (align 0x00001000)
    (owner "04-cache.wat:$handler_hist_record"))
  (region.declare $CODE_PAGE_BITMAP (size 0x00002000) (align 0x00001000)
    (owner "04-cache.wat:$code_page_mark"))
  (region.declare $SYNC_TABLE (size 0x00010000) (align 0x00001000)
    (owner "01-header.wat:$SYNC_TABLE"))
  (region.declare $D3DIM_VIEWPORT_LIGHT_HEAD (size 0x00008000) (align 0x00001000)
    (owner "09aa-handlers-d3dim.wat:$D3DIM_VIEWPORT_LIGHT_HEAD"))
  (region.declare $D3DIM_VIEWPORT_DATA (size 0x00008000) (align 0x00001000)
    (owner "09ab-handlers-d3dim-core.wat:$D3DIM_VIEWPORT_DATA"))
  (region.declare $HIT_COUNT_BASE (size 0x00000100) (align 0x00001000)
    (owner "01-header.wat:$HIT_COUNT_BASE"))
  ;; Eight I/O completion ports, each with a 256-entry queue of three dwords
  ;; (bytes transferred, completion key, OVERLAPPED*) after a 16-byte header.
  (region.declare $IOCP_TABLE (size 0x00008000) (align 0x00001000)
    (owner "01-header.wat:$IOCP_TABLE"))
  ;; +0x50..0x5F: the winmm timer thread (09a-handlers.wat $MM_TIMER_THREAD).
  (region.declare $TIMER_SHARED (size 0x00000060) (align 0x00000100)
    (owner "09a-handlers.wat:$timer_set"))
  (region.declare $EXTRA_CMDLINE_BUFFER (size 0x00000100) (align 0x00000100)
    (owner "10-helpers.wat:$EXTRA_CMDLINE_BUFFER"))
  (region.declare $TLS_NEXT_INDEX_SHARED (size 0x00000040) (align 0x00000100)
    (owner "01-header.wat:$TLS_NEXT_INDEX_SHARED"))
  (region.declare $DI_MOUSE_INPUT_STATE (size 0x00000118) (align 0x00000100)
    (owner "09a8-handlers-directx.wat:$di_mouse_delta_peek_x"))
  ;; One byte per WND_RECORDS slot: bits 0..1 are the horizontal ESB_* mask,
  ;; bits 2..3 are the vertical mask. Keeping arrow enablement beside, but
  ;; separate from, SCROLLINFO avoids stealing range/track bits from callers.
  ;; Declare it before the 4KB-aligned aux table so it occupies existing
  ;; allocator padding instead of moving every later region by a page.
  (region.declare $SCROLL_ARROW_TABLE (size 0x00000100) (align 0x00000100)
    (stride 0x1 (count $MAX_WINDOWS))
    (owner "09c0-window-table.wat:$scroll_arrow_mask_slot"))
  (region.declare $SCROLL_AUX_TABLE (size 0x00001000) (align 0x00001000)
    (owner "09c0-window-table.wat:$scroll_aux_addr"))
  (region.declare $TV_TABLE (size 0x00004000) (align 0x00001000)
    (stride 0x20 (count $TV_SLOT_COUNT))
    (owner "09c2-treeview.wat:$tv_find_slot"))
  (region.declare $TV_IMAGE_TABLE (size 0x00001000) (align 0x00001000)
    (owner "09c2-treeview.wat:$tv_image_record"))
  (region.declare $TV_OWNER_TABLE (size 0x00000800) (align 0x00001000)
    (stride 0x4 (count $TV_SLOT_COUNT))
    (owner "09c2-treeview.wat:$tv_owner_cell"))
  ;; The five DX_SURF_* tables and DX_CURSOR_SAVE are parallel-indexed to
  ;; DX_OBJECTS by $dx_slot_of, so every one of them is $DX_MAX records wide
  ;; and only the record size differs.
  ;; 16 bytes rather than 8: the third word is the surface's billed byte count.
  ;; It used to live in DxObject.misc2, which SetColorKey overwrites with the
  ;; colour key on the very same type-2 record -- so a keyed surface handed
  ;; $dx_vidmem_used its KEY back on release instead of its size, and the
  ;; difference never returned. Creation metadata belongs in the creation
  ;; metadata table, where nothing else writes it.
  (region.declare $DX_SURF_META (size 0x00020000) (align 0x00001000)
    (stride 0x10 (count $DX_MAX))
    (owner "09a8-handlers-directx.wat:$dx_surf_meta_ptr"))
  ;; The decoder's op-start list, PER GUEST THREAD: 8KB (2048 words) for each
  ;; of the 16 tids. Every loop matcher and x87 fuser reads it straight after
  ;; $te fills it, and guest threads are separate instances over this shared
  ;; memory that decode in parallel in worker mode -- one fixed list let
  ;; thread B's decode rewrite thread A's between A's $te and A's fuser, and
  ;; A's fuser then rewrote B's thread-cache records (Warcraft III, Miles MP3
  ;; thread, ?x87-fold --threads: an H451 island spanning non-x87 records ->
  ;; FPU_UNIMPL). $init_thread points $OP_INDEX at tid * 0x2000.
  (region.declare $OP_INDEX_REGION (size 0x00020000) (align 0x00001000)
    (stride 0x2000 (count $REGFILE_THREADS))
    (owner "01-header.wat:$OP_INDEX_REGION"))
  ;; Where the multi-block region MATCHER assembles a descriptor. It cannot
  ;; share OP_INDEX's far half the way the one-block matcher does: a region is
  ;; built across several consecutive $decode_block calls, and each of those
  ;; rewrites OP_INDEX from word 0 and runs the one-block matcher over the far
  ;; half. A region builder that lived there would be eaten by its own members.
  ;; 8192 words: 16 block records of 24, a 160-micro-op array, a fallback pool,
  ;; a thrash table and the size histogram in the first 4096, and the CFG
  ;; walker's own three tables -- worklist, per-head entry counters, per-head
  ;; failure memo -- in the second. See the $BX_RG_* offsets in
  ;; 07c-block-exec.wat, which are the only reader.
  (region.declare $BX_RG_BASE (size 0x00008000) (align 0x00001000)
    (stride 0x4 (count 8192))
    (owner "07c-block-exec.wat:$BX_RG_BASE"))
  ;; ROUND 13 -- the per-page OVERFLOW MEMO. 1024 direct-mapped slots of one
  ;; page base. A page whose chunk once overflowed is a page whose compiled
  ;; code does not fit in 16KB, and an executor descriptor is bigger than the
  ;; threaded stream it stands in for, so installing one there brings the next
  ;; overflow forward -- and an overflow DROPS THE WHOLE PAGE and re-decodes
  ;; every block on it. The memo has to outlive the page directory entry, which
  ;; is exactly what the drop destroys, so it cannot live in the page desc.
  (region.declare $PAGE_OVFL_MEMO (size 0x00001000) (align 0x00001000)
    (stride 0x4 (count 1024))
    (owner "04-cache.wat:$PAGE_OVFL_MEMO"))
  (region.declare $DX_SURF_PAL (size 0x00008000) (align 0x00001000)
    (stride 0x4 (count $DX_MAX))
    (owner "09a8-handlers-directx.wat:$dx_surf_pal_set"))
  (region.declare $DX_SURF_STATE (size 0x00040000) (align 0x00001000)
    (stride 0x20 (count $DX_MAX))
    (owner "09a8-handlers-directx.wat:$dx_surf_state_ptr"))
  (region.declare $DX_CURSOR_SAVE (size 0x00010000) (align 0x00001000)
    (stride 0x8 (count $DX_MAX))
    (owner "09a8-handlers-directx.wat:$dx_cursor_state_ptr"))
  ;; Harness-only. The worker-thread tests rendezvous here and the GDI region
  ;; tests marshal a RECT and a POINT array through it; no WAT reads any of it.
  ;; Declared for the reason everything else here is: every one of these cells
  ;; used to be a raw address picked out of a hole, or out of somebody else's
  ;; table, and both are free only until something moves.
  (region.declare $TEST_SCRATCH (size 0x00000100) (align 0x00001000)
    (owner "test/test-wat-window-tables.js:$TEST_SCRATCH"))
  (region.declare $DX_OBJECTS (size 0x00040000) (align 0x00001000)
    (stride $DX_ENTRY_SIZE (count $DX_MAX))
    (owner "09a8-handlers-directx.wat:$dx_alloc"))
  (region.declare $COM_WRAPPERS (size 0x00010000) (align 0x00001000)
    (owner "09a8-handlers-directx.wat:$dx_alloc_locked"))
  (region.declare $DX_SURF_FMT (size 0x00008000) (align 0x00001000)
    (stride 0x4 (count $DX_MAX))
    (owner "09a8-handlers-directx.wat:$dx_surf_fmt_ptr"))
  (region.declare $DX_SURF_OWNER (size 0x00008000) (align 0x00001000)
    (stride 0x4 (count $DX_MAX))
    (owner "09a8-handlers-directx.wat:$dx_surf_owner_ptr"))
  ;; Working space for one GL triangle on its way to the rasterizer: the
  ;; modelview-projection product, the vertex being transformed, three 32-byte
  ;; screen records, three 48-byte clip records and the up-to-four records
  ;; near-plane clipping leaves, then at +0x300 the default viewport a draw
  ;; with no glViewport maps through, +0x310 the far-clipped records and at
  ;; +0x400 the lighting normal matrix and per-vertex vectors. 1152 bytes
  ;; used of 2048.
  (region.declare $GL_SW_SCRATCH (size 0x00000800) (align 0x00001000)
    (owner "09a8g-gl-raster.wat:$gl_sw_scratch"))
  ;; The GL state the software rasterizer decides pixels by: a 64-byte block
  ;; at +0, then sixteen 96-byte glPushAttrib frames at +64 (1600 bytes).
  (region.declare $GL_SW_STATE (size 0x00000700) (align 0x00000100)
    (owner "09a8g-gl-raster.wat:$gl_sw_st"))
  ;; GL matrix-mirror context records: an atomic claim counter at +0, then from
  ;; +0x40 a 16-byte list node plus the 10832-byte block (09a8f's header),
  ;; 0x2C00 apart, for the first eight contexts.
  (region.declare $GL_MTX_BLOCKS (size 0x00017000) (align 0x00001000)
    (owner "09a8f-gl-matrix.wat:$gl_mtx_slot"))
  ;; One 8-byte slot per GL texture name below 4096: surface COM object, flags.
  (region.declare $GL_SW_TEXTURES (size 0x00008000) (align 0x00001000)
    (stride 0x8 (count 4096))
    (owner "09a8g-gl-raster.wat:$gl_sw_tex_slot"))
  ;; Mip levels 1..12 of each of those names, one surface COM object per
  ;; level (4096 needs twelve levels below level 0), 0 = not uploaded.
  (region.declare $GL_SW_MIPS (size 0x00030000) (align 0x00001000)
    (stride 0x30 (count 4096))
    (owner "09a8g-gl-raster.wat:$gl_sw_mip_at"))
  (region.declare $CP1252_TO_CP437 (size 0x00000100) (align 0x00001000)
    (owner "09a-handlers4-late.wat:$CP1252_TO_CP437"))
  (region.declare $CP437_TO_CP1252 (size 0x00000100) (align 0x00000100)
    (owner "09a-handlers4-late.wat:$CP437_TO_CP1252"))
  (region.declare $BRANCH_CMP_JCC_HIST (size 0x00001000) (align 0x00001000)
    (owner "04-cache.wat:$branch_hist_record_jcc"))
  (region.declare $BRANCH_TEST_JCC_HIST (size 0x00001000) (align 0x00001000)
    (owner "04-cache.wat:$branch_hist_record_jcc"))
  (region.declare $BRANCH_ALU_M32_RO_JCC_HIST (size 0x00008000) (align 0x00001000)
    (owner "04-cache.wat:$branch_hist_record_jcc"))
  ;; Both are open-addressed hash tables of 8-byte {key,count} records whose
  ;; probe masks the slot index, so the record count must stay a power of two.
  (region.declare $HOT_BLOCK_HIST (size 0x00040000) (align 0x00001000)
    (stride 0x8 (count $HOT_BLOCK_HIST_COUNT)) (size-is-power-of-2)
    (owner "04-cache.wat:$hot_block_hist_record"))
  (region.declare $SIB_CONSUMER_HIST (size 0x00010000) (align 0x00001000)
    (stride 0x8 (count $SIB_CONSUMER_HIST_COUNT)) (size-is-power-of-2)
    (owner "04-cache.wat:$sib_consumer_hist_record"))
  (region.declare $D3DIM_AUX (size 0x00001000) (align 0x00001000)
    (owner "09ab-handlers-d3dim-core.wat:$D3DIM_AUX"))
  (region.declare $D3D9_DEPTH_SERIAL (size 0x4) (align 0x4)
    (owner "09ak-d3d-depth.wat:$d3d9_depth_next_serial"))
  (region.declare $D3DIM_MATRICES (size 0x00004000) (align 0x00001000)
    (stride 0x40 (count $D3DIM_MATRIX_MAX))
    (owner "09a8-handlers-directx.wat:$D3DIM_MATRICES"))
  ;; NO (stride) LAW ON THE NEXT TWO, and both declines are structural, not
  ;; laziness. COM_WRAPPERS_AUX is $COM_WRAPPERS_AUX_MAX x 8 bytes ROUNDED UP
  ;; to a whole region (0x10004 vs 8192*8 = 0x10000): the tail is four bytes of
  ;; padding, so stride x count is deliberately less than the size, which is
  ;; exactly the shape a law refuses. DX_VTBL_REGISTRY carries a HEADER — its
  ;; size is ($DX_VTBL_REGISTRY_COUNT + 1) * 4, the +1 being the live count
  ;; stored at +0 — and a law over a headered table would have to lie about
  ;; either the stride or the count. test/test-wat-memory-map.js states both
  ;; relations as inequalities for that reason; that is where they belong.
  (region.declare $COM_WRAPPERS_AUX (size 0x00010004) (align 0x00001000)
    (owner "09a8-handlers-directx.wat:$dx_get_wrapper_for_vtbl_locked"))
  (region.declare $DX_VTBL_REGISTRY (size 0x00000138)
    (owner "09a8-handlers-directx.wat:$dx_vtable_registry_reset"))
  (region.declare $VSOCK_TABLE (size 0x00004000) (align 0x00001000)
    (stride $VSOCK_REC_SIZE (count $VSOCK_MAX))
    (owner "09d-winsock.wat:$vsock_rec"))
  ;; Per-process shell image-list identity plus the short immutable strings
  ;; SHGetFileInfo copies into SHFILEINFO.  WAT globals are per instance, so
  ;; the two HIMAGELIST handles themselves must live in shared memory for a
  ;; process whose API calls arrive through more than one Worker instance.
  (region.declare $SHELL_FILE_INFO (size 0x00000080) (align 0x00000010)
    (owner "09a9-comctl32.wat:$SHELL_FILE_INFO"))
  ;; One Win9x-style process/system DOS-device namespace.  The first page is
  ;; lock/header/string storage; the tail is 32 x 0x160-byte mapping records.
  ;; Keeping it in shared memory makes DefineDosDevice calls visible across
  ;; the main and Worker WASM instances without inventing host device I/O.
  (region.declare $DOS_DEVICE_NAMESPACE (size 0x00002D00) (align 0x00000010)
    (owner "09a0b-handlers-base-late.wat:$dos_device_record"))
  ;; Flat guest page table. One packed i32 per 4KB guest page covers
  ;; the complete 32-bit address space. Keep it outside $DIRECT_WINDOW: these
  ;; are emulator-private PTEs, never bytes a guest pointer may address. The
  ;; fixed 4MB tail is carved from the sparse backing pool instead of consuming
  ;; the layout-shake slack below 0x08000000.
  (region.declare-fixed $GUEST_PAGE_TABLE (base 0x1BC00000) (size 0x00400000) (align 0x00001000)
    (owner "01-header.wat:$GUEST_PAGE_TABLE"))
  (region.declare-fixed $VIRTUAL_BACKING_BASE (base 0x08000000) (size 0x12000000) (align 0x00001000)
    (owner "01-header.wat:$VIRTUAL_BACKING_BASE"))
  (region.declare-fixed $DIB_BACKING_BASE (base 0x1C000000) (size 0x03F00000) (align 0x00001000)
    (owner "10-helpers.wat:$dib_free_wasm"))
  (region.declare-fixed $THREAD_RPC (base 0x1FF00000) (size 0x00100000) (align 0x00001000)
    (owner "13-exports.wat:$run"))
  ;; $THREAD_RPC ends at 0x20000000, and the map ends with it. Everything above
  ;; that is the second sparse backing window -- see $virtual_backing_ext_base
  ;; in 10-helpers.wat, which is deliberately NOT a region: a region must fit
  ;; inside the import's INITIAL memory, and that window exists only on a host
  ;; that chose to create more than the 8192-page minimum.

  ;; ============================================================
  ;; SPANS — address-range LIMITS, not storage.
  ;;
  ;; A span names a boundary somebody's arithmetic tests against. It owns no
  ;; bytes, so it is TRANSPARENT to the overlap check: the regions it bounds
  ;; live inside it, which is the whole point and the one thing no other head
  ;; can express. It is never allocated and never shaken, and it has no
  ;; $NAME/$NAME_SIZE globals behind it — there is nothing to store — so
  ;; tools/check-region-decls.js neither requires nor reads one.
  ;; ============================================================

  ;; $g2w's direct guest window (docs/watx-region-safety-design.md §5.1). A
  ;; guest address translates by the flat `ga - image_base + GUEST_BASE` rule
  ;; only while the result lands below this limit; past it $g2w falls through to
  ;; the DIB window, then the sparse VirtualAlloc map, then NULL_SENTINEL. The
  ;; window is a UNION of regions — $GUEST_BASE, the guest heap, the stack, the
  ;; thunk zone, PE staging, the DLL tables and the whole WAT-private high map —
  ;; so it cannot be declared with any head that participates in the overlap
  ;; sweep. Its end is $VIRTUAL_BACKING_BASE's base: everything at or above
  ;; 0x08000000 is backing store reached through a translation, never directly.
  ;; Written as the bare literal 0x8000000 three times in 03-registers.wat until
  ;; this declaration; those three sites now spell it (region.end $DIRECT_WINDOW).
  (region.declare-span $DIRECT_WINDOW (base 0x00000000) (end 0x08000000)
    (owner "03-registers.wat:$g2w"))

  ;; Append new allocations to preserve existing canonical placements. Moving
  ;; these to the front exposed a Win16 Rodent runtime-DLL startup failure;
  ;; the browser Worker regression covers that layout-sensitive path.
  ;; Ownership is independent of the allocator's chosen addresses.
  ;; 1KB per thread, sixteen threads: main plus the fifteen worker partitions
  ;; $THREAD_CACHE_BASE carves.
  (region.declare $LOCAL_POST_QUEUES (size 0x00004000) (align 0x00000010)
    (owner "10-helpers.wat:$post_queue_base"))
  (region.declare $HEAP_ARENAS (size 0x00004010) (align 0x00000010)
    (owner "10-helpers.wat:$heap_arena_register"))
  ;; One process token plus 32 independently closeable handles.  The records
  ;; are emulator-private shared state; the tail holds the immutable classic
  ;; privilege names used by LookupPrivilegeValueA.
  (region.declare $TOKEN_OBJECTS (size 0x00000500) (align 0x00000010)
    (owner "09a0-handlers-base.wat:$token_record_addr"))
  ;; SetupAPI device-information sets are opaque USER-visible handles backed by
  ;; emulator-private shared records.  Generation bits keep a destroyed handle
  ;; stale even after its slot is reused by another Worker instance.
  (region.declare $SETUPDI_INFO_SETS (size 0x00000400) (align 0x00000010)
    (stride 0x20 (count $SETUPDI_INFO_SET_COUNT))
    (owner "09a7-handlers-dispatch.wat:$setupdi_record_addr"))
  ;; RegisterDeviceNotification returns an opaque HDEVNOTIFY whose lifetime is
  ;; shared by every thread in the process.  Keep caller-independent metadata
  ;; separate from the guest-readable WM_DEVICECHANGE payloads: applications
  ;; may inspect or temporarily alter lParam bytes while a message is handled,
  ;; but cannot thereby forge registration ownership.
  (region.declare $DEVICE_NOTIFY_RECORDS (size 0x00000600) (align 0x00000010)
    (stride 0x30 (count $DEVICE_NOTIFY_RECORD_COUNT))
    (owner "09a7-handlers-dispatch.wat:$device_notify_record_addr"))
  (region.declare $DEVICE_NOTIFY_PAYLOADS (size 0x00000400) (align 0x00000010)
    (stride 0x20 (count $DEVICE_NOTIFY_RECORD_COUNT))
    (owner "09a7-handlers-dispatch.wat:$device_notify_payload_addr"))
  ;; The original shared USER queue allocation covered thread ids 1..8. Keep
  ;; those addresses stable and append the remaining eight slots instead of
  ;; resizing the old declaration and moving every region allocated after it.
  (region.declare $THREAD_MSG_QUEUES_HIGH (size 0x00002080) (align 0x00000100)
    (stride $THREAD_MSG_QUEUE_STRIDE (count 8))
    (owner "09a-handlers.wat:$thread_msg_queue_addr"))
  ;; Process-shared CRT stream ownership: recursive lock at +0/+4, list at +8.
  (region.declare $CRT_STREAM_STATE (size 0x00000010) (align 0x00000010)
    (owner "09a6-handlers-crt.wat:$CRT_STREAM_STATE"))
  ;; Video for Windows decompressors: HIC table, ICINFO names and one
  ;; output row; per-stream workspaces come from $dib_alloc (09a7g-video-icm.wat header).
  (region.declare $VIDEO_ARENA (size 0x00005000) (align 0x00000010)
    (owner "09a7g-video-icm.wat:$VIDEO_ARENA"))
  ;; AVIFile reader: open files and streams, hdrl parse scratch
  ;; (09a7f-video-avi.wat header); chunk tables come from $dib_alloc.
  (region.declare $AVI_TABLE (size 0x00000680) (align 0x00000010)
    (owner "09a7f-video-avi.wat:$AVI_TABLE"))
  ;; MCI avivideo devices, command tokens, return staging and keywords.
  (region.declare $MCIAVI_TABLE (size 0x00001000) (align 0x00000010)
    (owner "09a7h-video-mciavi.wat:$MCIAVI_TABLE"))
  (region.declare $MCIWND_TABLE (size 0x00000800) (align 0x00000010)
    (owner "09a7i-video-mciwnd.wat:$MCIWND_TABLE"))
  ;; Native CRT export overrides that can hand a call back to the authentic
  ;; export: +0 entry count, +4 "setlocale changed the locale" flag, then
  ;; 127 [thunk index, authentic export VA] pairs -- UT2003 needs 11, because
  ;; Unreal funnels its CRT use through core.dll wrappers. Process-shared
  ;; because a DLL can load on any guest thread (09a6-handlers-crt.wat
  ;; header). Kept small: the map below 0x08000000 has almost no room left.
  (region.declare $CRT_OVERRIDE_TABLE (size 0x00000400) (align 0x00000010)
    (owner "09a6-handlers-crt.wat:$CRT_OVERRIDE_TABLE"))
  ;; Glide 2 process-shared board, lock, immutable stream and packet staging.
  ;; Fixed state uses 532 bytes; streams, texture payloads and LFB live on heap.
  (region.declare $GLIDE_STATE (size 0x00000220) (align 0x00000010)
    (owner "09a8h-glide.wat:$GLIDE_STATE"))
  ;; Lazy surface barriers shared by guest instances, never initialized by data.
  (region.declare $D3DIM_LAZY_SHARED (size 0x00000020) (align 0x00000010)
    (owner "09ab-handlers-d3dim-core.wat:$D3DIM_LAZY_SHARED"))

  (region.declare $GETMESSAGE_HOOKS (size 0x00000100) (align 0x00000010)
    (owner "09a-handlers4-late.wat:$getmessage_hook_state"))

  ;; Desktop depth and the lazy physical palette pointer, shared by all threads.
  (region.declare $GDI_DISPLAY_STATE (size 0x00000010) (align 0x00000010)
    (owner "10e-gdi-metafile.wat:$GDI_DISPLAY_STATE"))

  ;; Toolhelp heap registry; bucket storage is allocated lazily.
  (region.declare $TOOLHELP_HEAPS (size 0x00000010) (align 0x00000010)
    (owner "09a0d-toolhelp.wat:$TOOLHELP_HEAPS"))

  ;; Shared immutable descriptors for API entries patched by the guest.
  (region.declare $THUNK_PATCH_STATE (size 0x00000010) (align 0x00000010)
    (owner "09a0e-process-memory.wat:$THUNK_PATCH_STATE"))

  ;; DirectPlay session state (message and player tables, the network session),
  ;; one copy per process. Guest threads run their own module instance, and a
  ;; game may Receive on a thread of its own: MCM's network thread saw an empty
  ;; message table while the main instance queued every arriving frame.
  (region.declare $DP_SHARED (size 0x00000080) (align 0x00000010)
    (owner "09d4-dplay-net.wat:$DP_SHARED"))

  ;; Immutable launch identity, published before any guest thread starts.
  (region.declare $PROCESS_IMAGE_STATE (size 0x00000090) (align 0x00000010)
    (owner "13-exports.wat:$PROCESS_IMAGE_STATE"))
