;; Generated by tools/gen-gl-encoder-abi.js; do not edit.
;; Source: lib/gl-command-stream.js ARG_WORDS and BARRIERS.
(func $gl_arg_words (param $op i32) (result i32)
  (block $invalid
    (block $words18
    (block $words12
    (block $words9
    (block $words8
    (block $words7
    (block $words6
    (block $words4
    (block $words3
    (block $words2
    (block $words1
    (block $words0
      (br_table $words2 $words2 $words1 $words4 $words1 $words1 $words1 $words4 $words1 $words1 $words1 $words0 $words0 $words2 $words1 $words1 $words2 $words7 $words4 $words1 $words4 $words1 $words0 $words3 $words1 $words4 $words1 $words1 $words2 $words2 $words3 $words1 $words12 $words0 $words1 $words1 $words12 $words0 $words0 $words4 $words3 $words3 $words2 $words2 $words3 $words9 $words3 $words9 $words1 $words1 $words1 $words2 $words2 $words4 $words3 $words1 $words4 $words2 $words1 $words8 $words18 $words7 $words8 $words3 $words1 $words1 $words2 $words3 $words3 $words2 $words2 $words3 $words3 $words2 $words2 $words2 $words1 $words0 $words2 $words2 $words2 $words1 $words3 $words3 $words3 $words3 $words1 $words1 $words4 $words3 $words8 $words1 $words3 $words0 $words1 $words1 $words3 $words2 $words6 $words1 $words4 $words4 $words4 $words2 $words1 $words1 $words1 $words3 $words3 $words1 $words2 $words3 $words3 $words3 $words4 $words4 $invalid (local.get $op))
    ) (return (i32.const 0))
    ) (return (i32.const 1))
    ) (return (i32.const 2))
    ) (return (i32.const 3))
    ) (return (i32.const 4))
    ) (return (i32.const 6))
    ) (return (i32.const 7))
    ) (return (i32.const 8))
    ) (return (i32.const 9))
    ) (return (i32.const 12))
    ) (return (i32.const 18))
  )
  (i32.const -1))

(func $gl_is_barrier (param $op i32) (result i32)
  (block $no
    (block $yes
      (br_table $no $no $no $no $no $no $no $no $no $no $no $yes $yes $yes $no $no $no $yes $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $yes $yes $yes $yes $yes $yes $yes $yes $no $no $no $no $no $no $no $no $no $yes $no $no $no $no $no $no $no $no $yes $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $no $yes $no $no $no $no $no $no $no $no $no $yes $no $no $no $no $no $no $no $no $no $yes $yes $yes $no (local.get $op))
    ) (return (i32.const 1))
  )
  (i32.const 0))
