;; Reset transaction: all new native owners are allocated before the ordered
;; backend reset. The old device remains authoritative until completion.
;; Plan64: device,newProgram,newRT,newDepth,oldProgram,oldRT,pp,newD3DIM;
;; width,height,format,windowed,hwnd,autoDepth,autoFormat,presentInterval.
(func $d3d9_reset_dispose (param $plan i32)
  (local $wa i32) (local $program i32)
  (if (i32.eqz (local.get $plan)) (then (return)))
  (local.set $wa (call $g2w (local.get $plan)))
  (local.set $program (i32.load offset=4 (local.get $wa)))
  (if (local.get $program) (then
    (call $heap_free (call $gl32 (i32.add (local.get $program) (i32.const 1680)))) (call $heap_free (local.get $program))))
  (if (i32.load offset=8 (local.get $wa)) (then (drop (call $dx_surface_release (i32.load offset=8 (local.get $wa))))))
  (call $heap_free (i32.load offset=12 (local.get $wa)))
  (call $heap_free (i32.load offset=28 (local.get $wa)))
  (call $heap_free (local.get $plan)))
(func $d3d9_reset_preserve (param $dest i32) (param $source i32) (param $offset i32)
  (i32.store (i32.add (local.get $dest) (local.get $offset)) (i32.load (i32.add (local.get $source) (local.get $offset)))))
(func $d3d9_reset (param $device i32) (param $pp i32)
  (local $state i32) (local $old i32) (local $plan i32) (local $wa i32) (local $rt i32)
  (local $width i32) (local $height i32) (local $format i32) (local $windowed i32) (local $hwnd i32)
  (local $auto i32) (local $autoformat i32) (local $result i32) (local $next i32) (local $entry i32)
  (local $i i32) (local $shared i32) (local $client i32) (local $swap i32) (local $refresh i32) (local $interval i32) (local $ppwa i32)
  (i32.store offset=0 (global.get $reg_base) (i32.const 0x8876086c))
  (local.set $state (call $d3d9_program_state (local.get $device)))
  (if (i32.eqz (local.get $state)) (then (return)))
  (local.set $old (call $g2w (local.get $state)))
  (local.set $plan (i32.load offset=21768 (local.get $old)))
  (block $issue
    (if (local.get $plan) (then
      (local.set $result (call $d3d_render_poll)) (br $issue)))
    (i32.store offset=21776 (local.get $old) (i32.const 1))
    (if (i32.or (i32.eqz (local.get $pp))
      (i32.ne (i32.load offset=21780 (local.get $old)) (global.get $current_thread_id))) (then (return)))
    (if (i32.gt_u (local.get $pp) (i32.const 0xffffffc8)) (then (return)))
    (local.set $ppwa (call $g2w (local.get $pp)))
    (if (i32.or (i32.eqz (call $d3d_shader_vm_range (local.get $ppwa) (i32.const 56)))
      (i32.ne (call $g2w (i32.add (local.get $pp) (i32.const 55))) (i32.add (local.get $ppwa) (i32.const 55)))) (then (return)))
    (if (i32.or (i32.load offset=21772 (local.get $old)) (i32.load offset=1740 (local.get $old))) (then (return)))
    (local.set $rt (call $d3ddev_rt_entry (local.get $device)))
    (if (i32.ne (load.field DxObject refcount (local.get $rt)) (i32.const 1)) (then (return)))
    (if (i32.and (load.field DxObject flags (local.get $rt)) (i32.const 0x40000000)) (then (return)))
    (local.set $width (call $gl32 (local.get $pp))) (local.set $height (call $gl32 (i32.add (local.get $pp) (i32.const 4))))
    (local.set $format (call $gl32 (i32.add (local.get $pp) (i32.const 8))))
    (local.set $windowed (call $gl32 (i32.add (local.get $pp) (i32.const 32))))
    (local.set $hwnd (call $gl32 (i32.add (local.get $pp) (i32.const 28))))
    (if (i32.eqz (local.get $hwnd)) (then (local.set $hwnd (i32.load offset=1684 (local.get $old)))))
    ;; One physical back buffer supports DISCARD and COPY, not FLIP's extra
    ;; front/back ownership. Only LOCKABLE_BACKBUFFER is supported among flags.
    (local.set $swap (call $gl32 (i32.add (local.get $pp) (i32.const 24))))
    (if (i32.and (i32.ne (local.get $swap) (i32.const 1)) (i32.ne (local.get $swap) (i32.const 3))) (then (return)))
    (if (i32.and (call $gl32 (i32.add (local.get $pp) (i32.const 44))) (i32.const -2)) (then (return)))
    (local.set $refresh (call $gl32 (i32.add (local.get $pp) (i32.const 48))))
    (if (local.get $windowed)
      (then (if (local.get $refresh) (then (return))))
      (else (if (i32.and (i32.ne (local.get $refresh) (i32.const 0)) (i32.ne (local.get $refresh) (i32.const 60))) (then (return)))))
    (local.set $interval (call $gl32 (i32.add (local.get $pp) (i32.const 52))))
    (if (i32.and (i32.ne (local.get $interval) (i32.const 0))
      (i32.and (i32.ne (local.get $interval) (i32.const 1)) (i32.ne (local.get $interval) (i32.const 0x80000000)))) (then (return)))
    (if (i32.or (i32.gt_u (call $gl32 (i32.add (local.get $pp) (i32.const 12))) (i32.const 1))
      (i32.or (call $gl32 (i32.add (local.get $pp) (i32.const 16)))
        (call $gl32 (i32.add (local.get $pp) (i32.const 20))))) (then (return)))
    (if (i32.eqz (local.get $format)) (then
      (if (i32.eqz (local.get $windowed)) (then (return))) (local.set $format (i32.const 22))))
    (if (i32.eqz (call $d3d9_color_target_format (local.get $format))) (then (return)))
    (if (i32.or (i32.eqz (local.get $width)) (i32.eqz (local.get $height))) (then
      (if (i32.eqz (local.get $windowed)) (then (return)))
      (local.set $client (call $host_get_window_client_size (local.get $hwnd)))
      (if (i32.eqz (local.get $width)) (then (local.set $width (i32.and (local.get $client) (i32.const 65535)))))
      (if (i32.eqz (local.get $height)) (then (local.set $height (i32.shr_u (local.get $client) (i32.const 16)))))))
    (if (i32.or (i32.eqz (local.get $width)) (i32.or (i32.eqz (local.get $height))
      (i32.or (i32.gt_u (local.get $width) (i32.const 2048)) (i32.gt_u (local.get $height) (i32.const 2048))))) (then (return)))
    (if (i32.eqz (local.get $windowed)) (then
      (block $mode_found
        (loop $modes
          (br_if $mode_found (i32.and (i32.eq (local.get $width) (call $d3d9_mode_width (local.get $i)))
            (i32.eq (local.get $height) (call $d3d9_mode_height (local.get $i)))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br_if $modes (i32.lt_u (local.get $i) (call $d3d9_mode_count (i32.const 22)))))
        (return))
      (local.set $i (i32.const 0))))
    (local.set $auto (i32.ne (call $gl32 (i32.add (local.get $pp) (i32.const 36))) (i32.const 0)))
    (local.set $autoformat (call $gl32 (i32.add (local.get $pp) (i32.const 40))))
    (if (i32.and (local.get $auto) (i32.eqz (call $d3d9_depth_format (local.get $autoformat)))) (then (return)))
    (i32.store offset=0 (global.get $reg_base) (i32.const 0x8007000e))
    (local.set $plan (call $heap_alloc (i32.const 64)))
    (if (i32.eqz (local.get $plan)) (then (return)))
    (local.set $wa (call $g2w (local.get $plan))) (memory.fill (local.get $wa) (i32.const 0) (i32.const 64))
    (i32.store (local.get $wa) (local.get $device))
    (i32.store offset=16 (local.get $wa) (local.get $state))
    (i32.store offset=20 (local.get $wa) (call $d3dim_primary_guest (local.get $rt)))
    (i32.store offset=24 (local.get $wa) (local.get $pp))
    (i32.store offset=32 (local.get $wa) (local.get $width)) (i32.store offset=36 (local.get $wa) (local.get $height))
    (i32.store offset=40 (local.get $wa) (local.get $format)) (i32.store offset=44 (local.get $wa) (local.get $windowed))
    (i32.store offset=48 (local.get $wa) (local.get $hwnd)) (i32.store offset=52 (local.get $wa) (local.get $auto))
    (i32.store offset=56 (local.get $wa) (local.get $autoformat))
    (i32.store offset=60 (local.get $wa) (local.get $interval))
    (block $allocation_failed
      (i32.store offset=4 (local.get $wa) (call $d3d9_program_alloc))
      (br_if $allocation_failed (i32.eqz (i32.load offset=4 (local.get $wa))))
      (i32.store offset=8 (local.get $wa) (call $d3d9_create_surface (local.get $width) (local.get $height)
        (i32.mul (call $d3d9_color_bytes (local.get $format)) (i32.const 8))
        (i32.or (i32.const 1) (i32.shl (i32.and (call $gl32 (i32.add (local.get $pp) (i32.const 44))) (i32.const 1)) (i32.const 27)))))
      (br_if $allocation_failed (i32.eqz (i32.load offset=8 (local.get $wa))))
      (i32.store offset=28 (local.get $wa) (call $heap_alloc (i32.const 4096)))
      (br_if $allocation_failed (i32.eqz (i32.load offset=28 (local.get $wa))))
      (call $d3ddev_init_state (i32.load offset=28 (local.get $wa)))
      (if (local.get $auto) (then
        (i32.store offset=12 (local.get $wa) (call $d3d9_depth_new (i32.const 0) (local.get $width) (local.get $height)
          (local.get $autoformat) (i32.const 0) (i32.const 0)))
        (br_if $allocation_failed (i32.eqz (i32.load offset=12 (local.get $wa))))))
      (i32.store offset=21768 (local.get $old) (local.get $plan))
      (local.set $result (call $host_gpu_gl_call (i32.const 0x30009) (local.get $wa) (local.get $device)))
      (br $issue))
    (call $d3d9_reset_dispose (local.get $plan)) (return))
  (if (call $d3d_render_park (local.get $result) (i32.const 0)) (then (return)))
  (local.set $wa (call $g2w (local.get $plan)))
  (i32.store offset=21768 (local.get $old) (i32.const 0))
  (if (i32.ne (local.get $result) (i32.const 1)) (then
    (call $d3d9_reset_dispose (local.get $plan)) (i32.store offset=0 (global.get $reg_base) (i32.const 0x88760868)) (return)))
  (local.set $next (call $g2w (i32.load offset=4 (local.get $wa))))
  ;; Preserve vtables needed by surviving shaders/managed resources and the
  ;; creation identity, but none of the old bindings or render state.
  (call $heap_free (i32.load offset=1680 (local.get $next)))
  (call $d3d9_reset_preserve (local.get $next) (local.get $old) (i32.const 1680))
  (call $d3d9_reset_preserve (local.get $next) (local.get $old) (i32.const 1716))
  (call $d3d9_reset_preserve (local.get $next) (local.get $old) (i32.const 1736))
  (call $d3d9_reset_preserve (local.get $next) (local.get $old) (i32.const 2064))
  (call $d3d9_reset_preserve (local.get $next) (local.get $old) (i32.const 21720))
  (call $d3d9_reset_preserve (local.get $next) (local.get $old) (i32.const 21724))
  (memory.copy (i32.add (local.get $next) (i32.const 20628)) (i32.add (local.get $old) (i32.const 20628)) (i32.const 36))
  (i32.store offset=25600 (local.get $next)
    (select (i32.const 23) (i32.const 22) (i32.eq (i32.load offset=40 (local.get $wa)) (i32.const 23))))
  (i32.store offset=1684 (local.get $next) (i32.load offset=48 (local.get $wa)))
  (i32.store offset=20648 (local.get $next) (i32.load offset=32 (local.get $wa)))
  (i32.store offset=20652 (local.get $next) (i32.load offset=36 (local.get $wa)))
  (i32.store offset=20660 (local.get $next) (i32.load offset=40 (local.get $wa)))
  (i32.store offset=21752 (local.get $next) (i32.load offset=12 (local.get $wa)))
  (i32.store offset=21756 (local.get $next) (i32.load offset=12 (local.get $wa)))
  (i32.store offset=21760 (local.get $next) (i32.load offset=56 (local.get $wa)))
  (i32.store offset=21764 (local.get $next) (i32.load offset=52 (local.get $wa)))
  (i32.store offset=21784 (local.get $next) (i32.load offset=60 (local.get $wa)))
  (call $d3d9_reset_preserve (local.get $next) (local.get $old) (i32.const 21788))
  (if (i32.load offset=44 (local.get $wa)) (then
    (i32.store offset=20648 (local.get $next) (i32.and (i32.load offset=21788 (local.get $next)) (i32.const 65535)))
    (i32.store offset=20652 (local.get $next) (i32.shr_u (i32.load offset=21788 (local.get $next)) (i32.const 16)))
    (i32.store offset=20660 (local.get $next) (i32.const 22))))
  (if (i32.load offset=12 (local.get $wa)) (then
    (call $gs32 (i32.add (i32.load offset=12 (local.get $wa)) (i32.const 8)) (local.get $device))
    (call $gs32 (i32.add (i32.load offset=12 (local.get $wa)) (i32.const 16)) (i32.const 2))))
  (local.set $entry (call $dx_from_this (local.get $device)))
  (local.set $shared (i32.load offset=16 (local.get $entry)))
  (store.field DxObject misc0 (local.get $entry) (call $dx_slot_of (call $dx_from_this (i32.load offset=8 (local.get $wa)))))
  (store.field DxObject misc1 (local.get $entry) (i32.load offset=4 (local.get $wa)))
  (i32.store offset=16 (local.get $entry) (i32.load offset=28 (local.get $wa)))
  (call $d3d9_default_output (local.get $device) (i32.load offset=52 (local.get $wa)))
  (call $d3d9_shader_unbind (i32.load (local.get $old))) (call $d3d9_shader_unbind (i32.load offset=4 (local.get $old)))
  (call $d3d9_shader_unbind (i32.load offset=8 (local.get $old)))
  (loop $textures
    (call $d3d9_shader_unbind (i32.load (i32.add (local.get $old) (call $d3d9_texture_offset (local.get $i)))))
    (local.set $i (i32.add (local.get $i) (i32.const 1))) (br_if $textures (i32.lt_u (local.get $i) (i32.const 6))))
  (call $d3d9_shader_unbind (i32.load offset=1720 (local.get $old))) (call $d3d9_shader_unbind (i32.load offset=1732 (local.get $old)))
  (call $d3d9_depth_unbind (i32.load offset=21752 (local.get $old))) (call $d3d9_depth_unbind (i32.load offset=21756 (local.get $old)))
  (call $d3d9_lights_free (i32.load offset=21996 (local.get $old)))
  (call $d3d9_color_unbind (i32.load offset=22020 (local.get $old)))
  (call $heap_free (local.get $state)) (call $heap_free (local.get $shared))
  (drop (call $dx_surface_release (i32.load offset=20 (local.get $wa))))
  (global.set $d3d9_windowed_hwnd (select (i32.load offset=48 (local.get $wa)) (i32.const 0) (i32.load offset=44 (local.get $wa))))
  ;; Host-visible mode/window changes occur only after backend completion.
  (call $dx_coop_hwnd_set (i32.load offset=48 (local.get $wa)))
  (if (i32.load offset=44 (local.get $wa)) (then
    (call $dx_display_w_set (i32.and (i32.load offset=21788 (local.get $next)) (i32.const 65535)))
    (call $dx_display_h_set (i32.shr_u (i32.load offset=21788 (local.get $next)) (i32.const 16)))
    (call $dx_display_bpp_set (i32.const 32)) (call $dx_display_mode_set (i32.const 0))))
  (if (i32.eqz (i32.load offset=44 (local.get $wa))) (then
    (call $dx_display_w_set (i32.load offset=32 (local.get $wa)))
    (call $dx_display_h_set (i32.load offset=36 (local.get $wa)))
    (call $dx_display_bpp_set (i32.mul (call $d3d9_color_bytes (i32.load offset=40 (local.get $wa))) (i32.const 8)))
    (call $dx_display_mode_set (i32.const 1))
    (if (i32.load offset=48 (local.get $wa)) (then
      (call $host_move_window (i32.load offset=48 (local.get $wa)) (i32.const 0) (i32.const 0)
        (i32.load offset=32 (local.get $wa)) (i32.load offset=36 (local.get $wa)) (i32.const 0))))))
  (local.set $pp (i32.load offset=24 (local.get $wa)))
  (call $gs32 (local.get $pp) (i32.const 0)) (call $gs32 (i32.add (local.get $pp) (i32.const 4)) (i32.const 0))
  (call $gs32 (i32.add (local.get $pp) (i32.const 12)) (i32.const 0))
  (if (i32.load offset=44 (local.get $wa)) (then (call $gs32 (i32.add (local.get $pp) (i32.const 8)) (i32.const 0))))
  (call $heap_free (local.get $plan)) (i32.store offset=0 (global.get $reg_base) (i32.const 0)))
