;; Independent D3D9 color surfaces. The first48 bytes intentionally share the
;; depth surface external/internal ownership protocol, but never its backend ID
;; namespace. Header80: +40 CPU pixels,+48 pitch,+52 bytes,+56 lock flags,
;; +60 pool,+64 usage,+68 dirty serial. Device+22020 holds the bound RT0;
;; zero means the implicit backbuffer (DxObject.misc0), not a NULL RT0.
(func $d3d9_is_color_surface (param $surface i32) (result i32)
  (if (i32.eqz (local.get $surface)) (then (return (i32.const 0))))
  (i32.eq (call $gl32 (i32.add (local.get $surface) (i32.const 12))) (i32.const 0xd3d90006)))

;; Existing implicit surfaces predate heap color metadata and have no owner
;; backpointer. Resolve the live device by its retained backbuffer slot.
(func $d3d9_backbuffer_owner (param $surface i32) (result i32)
  (local $entry i32) (local $slot i32) (local $i i32) (local $p i32)
  (local.set $entry (call $dx_from_this (local.get $surface)))
  (if (i32.eqz (local.get $entry)) (then (return (i32.const 0))))
  (if (i32.ne (load.field DxObject type (local.get $entry)) (i32.const 2)) (then (return (i32.const 0))))
  (local.set $slot (call $dx_slot_of (local.get $entry)))
  (loop $devices
    (local.set $p (i32.add (global.get $DX_OBJECTS) (i32.mul (local.get $i) (global.get $DX_ENTRY_SIZE))))
    (if (i32.and (i32.eq (load.field DxObject type (local.get $p)) (i32.const 20))
      (i32.and (i32.ne (load.field DxObject misc1 (local.get $p)) (i32.const 0))
        (i32.eq (load.field DxObject misc0 (local.get $p)) (local.get $slot)))) (then
      ;; This is an internal owner identity, not QueryInterface. D3D8 changes
      ;; the primary device wrapper's vtable to Device8; requesting a Device9
      ;; wrapper here creates an alias and splits host rendering into two
      ;; devices (Present on the primary, LockRect/UnlockRect on the alias).
      (return (call $w2g (i32.add (global.get $COM_WRAPPERS)
        (i32.mul (local.get $i) (i32.const 8)))))))
    (local.set $i (i32.add (local.get $i) (i32.const 1)))
    (br_if $devices (i32.lt_u (local.get $i) (global.get $DX_MAX))))
  (i32.const 0))

;; Baseline surface reference1 belongs to the device. The first external
;; reference retains its parent; subsequent surface refs share that hold.
(func $d3d9_backbuffer_addref (param $surface i32) (result i32)
  (local $entry i32) (local $device i32) (local $parent i32) (local $refs i32)
  (local.set $entry (call $dx_from_this (local.get $surface)))
  (if (i32.eqz (local.get $entry)) (then (return (i32.const 0))))
  (local.set $refs (load.field DxObject refcount (local.get $entry)))
  (if (i32.eq (local.get $refs) (i32.const 1)) (then
    (local.set $device (call $d3d9_backbuffer_owner (local.get $surface)))
    (if (local.get $device) (then
      (local.set $parent (call $dx_from_this (local.get $device)))
      (store.field DxObject refcount (local.get $parent)
        (i32.add (load.field DxObject refcount (local.get $parent)) (i32.const 1)))))))
  (local.set $refs (i32.add (local.get $refs) (i32.const 1)))
  (store.field DxObject refcount (local.get $entry) (local.get $refs))
  (local.get $refs))

(func $d3d9_bound_dc_held (param $device i32) (result i32)
  (local $state i32)
  (local.set $state (call $d3d9_program_state (local.get $device)))
  (if (i32.eqz (local.get $state)) (then (return (i32.const 0))))
  (if (call $gl32 (i32.add (local.get $state) (i32.const 22020))) (then (return (i32.const 0))))
  (i32.ne (i32.and (load.field DxObject flags (call $d3ddev_rt_entry (local.get $device)))
    (i32.const 0x40000000)) (i32.const 0)))

(func $d3d9_backbuffer_dc_sync (param $device i32) (param $upload i32) (result i32)
  (local $desc i32) (local $result i32) (local $state i32)
  (if (global.get $d3d_render_token) (then (return (call $d3d_render_poll))))
  (local.set $desc (call $d3d9_gpu_descriptor (local.get $device)))
  (if (local.get $upload) (then
    (i32.store offset=24 (local.get $desc) (i32.const 0))
    (i32.store offset=28 (local.get $desc) (i32.load offset=8 (local.get $desc)))
    (i32.store offset=32 (local.get $desc) (i32.mul (i32.load offset=12 (local.get $desc)) (i32.const 4)))
    (i32.store offset=36 (local.get $desc) (i32.const 0)) (i32.store offset=44 (local.get $desc) (i32.const 0))
    (i32.store offset=48 (local.get $desc) (i32.load offset=12 (local.get $desc)))
    (i32.store offset=52 (local.get $desc) (i32.load offset=16 (local.get $desc)))
    (i32.store offset=56 (local.get $desc) (i32.const 22))
    (if (i32.and (load.field DxObject flags (call $d3ddev_rt_entry (local.get $device)))
      (i32.shl (i32.const 1) (i32.const 26))) (then
      (local.set $state (call $g2w (call $d3d9_program_state (local.get $device))))
      (i32.store offset=36 (local.get $desc) (i32.load offset=22028 (local.get $state)))
      (i32.store offset=44 (local.get $desc) (i32.load offset=22032 (local.get $state)))
      (i32.store offset=48 (local.get $desc) (i32.load offset=22036 (local.get $state)))
      (i32.store offset=52 (local.get $desc) (i32.load offset=22040 (local.get $state)))
      (i32.store offset=28 (local.get $desc) (i32.add (i32.load offset=28 (local.get $desc))
        (i32.add (i32.mul (i32.load offset=44 (local.get $desc)) (i32.load offset=32 (local.get $desc)))
          (i32.mul (i32.load offset=36 (local.get $desc)) (i32.const 4)))))))
    (return (call $host_gpu_gl_call (i32.const 0x30015) (local.get $desc) (i32.const 0)))))
  (call $host_gpu_gl_call (i32.const 0x30016) (local.get $desc) (i32.const 0)))

;; LockRect and GetDC share CPU exclusion, but remain distinct ownership kinds.
(func $d3d9_backbuffer_lock (param $surface i32) (param $out i32) (param $rect i32) (param $flags i32)
  (local $device i32) (local $entry i32) (local $dest i32) (local $rw i32)
  (local $left i32) (local $top i32) (local $result i32) (local $pitch i32)
  (local $state i32) (local $width i32) (local $height i32)
  (i32.store offset=0 (global.get $reg_base) (i32.const 0x8876086c))
  (local.set $device (call $d3d9_backbuffer_owner (local.get $surface)))
  (if (i32.eqz (local.get $device)) (then (return)))
  (local.set $entry (call $dx_from_this (local.get $surface)))
  (local.set $state (call $g2w (call $d3d9_program_state (local.get $device))))
  (block $snapshot
  (br_if $snapshot (global.get $d3d_render_token))
  (local.set $dest (call $d3d9_state_bytes (local.get $out) (i32.const 8)))
  (if (i32.eqz (local.get $dest)) (then (return)))
  (if (i32.eqz (i32.and (load.field DxObject flags (local.get $entry)) (i32.shl (i32.const 1) (i32.const 27)))) (then (return)))
  ;; READONLY and NOSYSLOCK; unsupported nonblocking/discard modes are explicit.
  (if (i32.and (local.get $flags) (i32.const 0xfffff7ef)) (then (return)))
  (local.set $width (load.field DxObject width (local.get $entry)))
  (local.set $height (load.field DxObject height (local.get $entry)))
  (if (local.get $rect) (then
    (local.set $rw (call $d3d9_state_bytes (local.get $rect) (i32.const 16)))
    (if (i32.eqz (local.get $rw)) (then (return)))
    (local.set $left (i32.load (local.get $rw))) (local.set $top (i32.load offset=4 (local.get $rw)))
    (if (i32.ge_u (local.get $left) (i32.load offset=8 (local.get $rw))) (then (return)))
    (if (i32.ge_u (local.get $top) (i32.load offset=12 (local.get $rw))) (then (return)))
    (if (i32.gt_u (i32.load offset=8 (local.get $rw)) (load.field DxObject width (local.get $entry))) (then (return)))
    (if (i32.gt_u (i32.load offset=12 (local.get $rw)) (load.field DxObject height (local.get $entry))) (then (return)))
    (local.set $width (i32.sub (i32.load offset=8 (local.get $rw)) (local.get $left)))
    (local.set $height (i32.sub (i32.load offset=12 (local.get $rw)) (local.get $top)))))
  (if (i32.eqz (global.get $d3d_render_token)) (then
    (if (i32.and (load.field DxObject flags (local.get $entry)) (i32.const 0x40000000)) (then (return)))
    (i32.store offset=22024 (local.get $state) (local.get $dest))
    (i32.store offset=22028 (local.get $state) (local.get $left))
    (i32.store offset=22032 (local.get $state) (local.get $top))
    (i32.store offset=22036 (local.get $state) (local.get $width))
    (i32.store offset=22040 (local.get $state) (local.get $height))
    (store.field DxObject flags (local.get $entry)
      (i32.or (load.field DxObject flags (local.get $entry))
        (i32.or (i32.const 0x64000000) (i32.shl (i32.and (local.get $flags) (i32.const 16)) (i32.const 21)))))))
  )
  (local.set $dest (i32.load offset=22024 (local.get $state)))
  (local.set $left (i32.load offset=22028 (local.get $state)))
  (local.set $top (i32.load offset=22032 (local.get $state)))
  (local.set $result (call $d3d9_backbuffer_dc_sync (local.get $device) (i32.const 0)))
  (if (call $d3d_render_park (local.get $result) (i32.const 0)) (then (return)))
  (store.field DxObject flags (local.get $entry)
    (i32.and (load.field DxObject flags (local.get $entry)) (i32.const 0xdfffffff)))
  (if (i32.ne (local.get $result) (i32.const 1)) (then
    (store.field DxObject flags (local.get $entry)
      (i32.and (load.field DxObject flags (local.get $entry)) (i32.const 0xb9ffffff))) (return)))
  (local.set $pitch (load.field DxObject pitch (local.get $entry)))
  (i32.store (local.get $dest) (local.get $pitch))
  (i32.store offset=4 (local.get $dest)
    (i32.add (call $w2g (load.field DxObject misc1 (local.get $entry)))
      (i32.add (i32.mul (local.get $top) (local.get $pitch)) (i32.mul (local.get $left) (i32.const 4)))))
  (i32.store offset=0 (global.get $reg_base) (i32.const 0)))

(func $d3d9_backbuffer_unlock (param $surface i32)
  (local $device i32) (local $entry i32) (local $flags i32) (local $result i32)
  (i32.store offset=0 (global.get $reg_base) (i32.const 0x8876086c))
  (local.set $device (call $d3d9_backbuffer_owner (local.get $surface)))
  (if (i32.eqz (local.get $device)) (then (return)))
  (local.set $entry (call $dx_from_this (local.get $surface)))
  (local.set $flags (load.field DxObject flags (local.get $entry)))
  (if (i32.eqz (i32.and (local.get $flags) (i32.shl (i32.const 1) (i32.const 26)))) (then (return)))
  (if (i32.and (local.get $flags) (i32.shl (i32.const 1) (i32.const 29))) (then (return)))
  (if (i32.eqz (i32.and (local.get $flags) (i32.shl (i32.const 1) (i32.const 25)))) (then
    (if (i32.eqz (global.get $d3d_render_token)) (then
      (if (i32.and (local.get $flags) (i32.shl (i32.const 1) (i32.const 28))) (then (return)))
      (store.field DxObject flags (local.get $entry) (i32.or (local.get $flags) (i32.shl (i32.const 1) (i32.const 28))))))
    (local.set $result (call $d3d9_backbuffer_dc_sync (local.get $device) (i32.const 1)))
    (if (call $d3d_render_park (local.get $result) (i32.const 0)) (then (return)))
    (store.field DxObject flags (local.get $entry)
      (i32.and (load.field DxObject flags (local.get $entry)) (i32.const 0xefffffff)))
    (if (i32.ne (local.get $result) (i32.const 1)) (then (return)))))
  (store.field DxObject flags (local.get $entry)
    (i32.and (load.field DxObject flags (local.get $entry)) (i32.const 0xb9ffffff)))
  (i32.store offset=0 (global.get $reg_base) (i32.const 0)))

;; Embedded storage descriptors are not COM objects. The existing 20-byte
;; surface view owns the external reference; bindings retain its parent texture.
;; +72 parent texture and +76 face-major mip index distinguish these records.
(func $d3d9_texture_colors_init (param $texture i32) (param $count i32) (result i32)
  (local $wa i32) (local $base i32) (local $record i32) (local $mip i32)
  (local $i i32) (local $serial i32)
  (local.set $wa (call $g2w (local.get $texture)))
  (local.set $base (i32.add (local.get $texture)
    (i32.add (i32.const 64) (i32.mul (local.get $count) (i32.const 32)))))
  (loop $levels
    (local.set $serial (call $d3d9_depth_next_serial))
    (if (i32.eqz (local.get $serial)) (then (return (i32.const 0))))
    (local.set $record (call $g2w (i32.add (local.get $base) (i32.mul (local.get $i) (i32.const 80)))))
    (local.set $mip (call $d3d9_texture_mip (local.get $texture) (local.get $i)))
    (i32.store offset=8 (local.get $record) (i32.load offset=8 (local.get $wa)))
    (i32.store offset=12 (local.get $record) (i32.const 0xd3d90006))
    (i32.store offset=20 (local.get $record) (i32.load (local.get $mip)))
    (i32.store offset=24 (local.get $record) (i32.load offset=4 (local.get $mip)))
    (i32.store offset=28 (local.get $record) (i32.load offset=36 (local.get $wa)))
    (i32.store offset=36 (local.get $record) (local.get $serial))
    (i32.store offset=40 (local.get $record) (i32.load offset=16 (local.get $mip)))
    (i32.store offset=48 (local.get $record) (i32.load offset=8 (local.get $mip)))
    (i32.store offset=52 (local.get $record) (i32.load offset=12 (local.get $mip)))
    (i32.store offset=64 (local.get $record) (i32.const 1))
    (i32.store offset=72 (local.get $record) (local.get $texture))
    (i32.store offset=76 (local.get $record) (local.get $i))
    (local.set $i (i32.add (local.get $i) (i32.const 1)))
    (br_if $levels (i32.lt_u (local.get $i) (local.get $count))))
  ;; Publish only after all identities have been allocated successfully.
  (i32.store offset=56 (local.get $wa) (local.get $base))
  (i32.const 1))

(func $d3d9_color_storage (param $surface i32) (result i32)
  (local $parent i32) (local $index i32) (local $base i32)
  (if (call $d3d9_is_color_surface (local.get $surface)) (then (return (local.get $surface))))
  (if (i32.eqz (local.get $surface)) (then (return (i32.const 0))))
  (if (i32.ne (call $gl32 (i32.add (local.get $surface) (i32.const 12)))
    (i32.const 0xd3d90001)) (then (return (i32.const 0))))
  (local.set $parent (call $gl32 (i32.add (local.get $surface) (i32.const 8))))
  (local.set $index (call $gl32 (i32.add (local.get $surface) (i32.const 16))))
  (if (i32.eqz (call $d3d9_texture_mip (local.get $parent) (local.get $index))) (then (return (i32.const 0))))
  (local.set $base (call $gl32 (i32.add (local.get $parent) (i32.const 56))))
  (if (i32.eqz (local.get $base)) (then (return (i32.const 0))))
  (i32.add (local.get $base) (i32.mul (local.get $index) (i32.const 80))))

(func $d3d9_color_unbind (param $surface i32)
  (local $wa i32) (local $parent i32)
  (if (i32.eqz (local.get $surface)) (then (return)))
  (local.set $wa (call $g2w (local.get $surface)))
  (local.set $parent (i32.load offset=72 (local.get $wa)))
  (if (i32.eqz (local.get $parent)) (then (call $d3d9_depth_unbind (local.get $surface)) (return)))
  (if (i32.eqz (i32.load offset=16 (local.get $wa))) (then (return)))
  (i32.store offset=16 (local.get $wa) (i32.sub (i32.load offset=16 (local.get $wa)) (i32.const 1)))
  (call $d3d9_shader_unbind (local.get $parent)))

(func $d3d9_color_create (param $device i32) (param $width i32) (param $height i32)
  (param $format i32) (param $pool i32) (param $usage i32) (param $lockable i32) (param $out i32)
  (local $surface i32) (local $wa i32) (local $bytes i32) (local $serial i32)
  (i32.store offset=0 (global.get $reg_base) (i32.const 0x8876086c))
  (if (i32.eqz (call $d3d9_state_bytes (local.get $out) (i32.const 4))) (then (return)))
  (call $gs32 (local.get $out) (i32.const 0))
  (if (i32.eqz (call $d3d9_program_state (local.get $device))) (then (return)))
  (if (i32.or (i32.eqz (local.get $width)) (i32.or (i32.eqz (local.get $height))
    (i32.or (i32.gt_u (local.get $width) (i32.const 2048)) (i32.gt_u (local.get $height) (i32.const 2048))))) (then (return)))
  (if (i32.eqz (i32.or (i32.eq (local.get $format) (i32.const 21))
    (i32.eq (local.get $format) (i32.const 22)))) (then (return)))
  (if (i32.or (i32.eq (local.get $pool) (i32.const 1)) (i32.gt_u (local.get $pool) (i32.const 3))) (then (return)))
  (local.set $bytes (i32.mul (i32.mul (local.get $width) (local.get $height)) (i32.const 4)))
  (i32.store offset=0 (global.get $reg_base) (i32.const 0x8007000e))
  (local.set $serial (call $d3d9_depth_next_serial))
  (if (i32.eqz (local.get $serial)) (then (return)))
  (local.set $surface (call $heap_alloc (i32.add (i32.const 80) (local.get $bytes))))
  (if (i32.eqz (local.get $surface)) (then (return)))
  (local.set $wa (call $g2w (local.get $surface)))
  (memory.fill (local.get $wa) (i32.const 0) (i32.add (i32.const 80) (local.get $bytes)))
  (i32.store (local.get $wa) (global.get $DX_VTBL_D3DSURF9))
  (i32.store offset=8 (local.get $wa) (local.get $device))
  (i32.store offset=12 (local.get $wa) (i32.const 0xd3d90006))
  (i32.store offset=20 (local.get $wa) (local.get $width))
  (i32.store offset=24 (local.get $wa) (local.get $height))
  (i32.store offset=28 (local.get $wa) (local.get $format))
  (i32.store offset=32 (local.get $wa) (local.get $lockable))
  (i32.store offset=36 (local.get $wa) (local.get $serial))
  (i32.store offset=40 (local.get $wa) (i32.add (local.get $surface) (i32.const 80)))
  (i32.store offset=48 (local.get $wa) (i32.mul (local.get $width) (i32.const 4)))
  (i32.store offset=52 (local.get $wa) (local.get $bytes))
  (i32.store offset=60 (local.get $wa) (local.get $pool))
  (i32.store offset=64 (local.get $wa) (local.get $usage))
  (drop (call $d3d9_depth_addref (local.get $surface)))
  (call $gs32 (local.get $out) (local.get $surface))
  (i32.store offset=0 (global.get $reg_base) (i32.const 0)))

;; ColorFill names its destination independently of the bound render target.
;; The existing descriptor's draw-only fields carry a copied rectangle/color;
;; the host snapshots these into an ordinary ordered CLEAR command.
(func $d3d9_color_fill (param $device i32) (param $surface i32) (param $rect i32) (param $color i32)
  (local $storage i32) (local $wa i32) (local $rt i32) (local $width i32) (local $height i32)
  (local $rw i32) (local $left i32) (local $top i32) (local $right i32) (local $bottom i32)
  (local $desc i32) (local $result i32)
  (i32.store offset=0 (global.get $reg_base) (i32.const 0x8876086c))
  (if (i32.eqz (call $d3d9_program_state (local.get $device))) (then (return)))
  (local.set $storage (call $d3d9_color_storage (local.get $surface)))
  (if (local.get $storage) (then
    (local.set $wa (call $g2w (local.get $storage)))
    (if (i32.ne (i32.load offset=8 (local.get $wa)) (local.get $device)) (then (return)))
    (if (i32.or (i32.load offset=60 (local.get $wa)) (i32.load offset=56 (local.get $wa))) (then (return)))
    (local.set $width (i32.load offset=20 (local.get $wa)))
    (local.set $height (i32.load offset=24 (local.get $wa))))
  (else
    (local.set $rt (call $d3ddev_rt_entry (local.get $device)))
    (if (i32.ne (local.get $surface) (call $dx_get_wrapper_for_vtbl
      (call $dx_slot_of (local.get $rt)) (global.get $DX_VTBL_D3DSURF9))) (then (return)))
    (if (i32.eqz (local.get $surface)) (then (return)))
    (if (i32.and (i32.eqz (global.get $d3d_render_token))
      (i32.ne (i32.and (load.field DxObject flags (local.get $rt)) (i32.const 0x40000000)) (i32.const 0))) (then (return)))
    (local.set $width (load.field DxObject width (local.get $rt)))
    (local.set $height (load.field DxObject height (local.get $rt)))))
  (local.set $right (local.get $width)) (local.set $bottom (local.get $height))
  (if (local.get $rect) (then
    (local.set $rw (call $d3d9_state_bytes (local.get $rect) (i32.const 16)))
    (if (i32.eqz (local.get $rw)) (then (return)))
    (local.set $left (i32.load (local.get $rw))) (local.set $top (i32.load offset=4 (local.get $rw)))
    (local.set $right (i32.load offset=8 (local.get $rw))) (local.set $bottom (i32.load offset=12 (local.get $rw)))
    (if (i32.or (i32.ge_u (local.get $left) (local.get $right))
      (i32.ge_u (local.get $top) (local.get $bottom))) (then (return)))
    (if (i32.or (i32.gt_u (local.get $right) (local.get $width))
      (i32.gt_u (local.get $bottom) (local.get $height))) (then (return)))))
  (local.set $result (if (result i32) (global.get $d3d_render_token)
    (then (call $d3d_render_poll))
    (else
      (local.set $desc (call $d3d9_gpu_descriptor (local.get $device)))
      (i32.store offset=24 (local.get $desc) (local.get $storage))
      (i32.store offset=28 (local.get $desc) (local.get $color))
      (i32.store offset=32 (local.get $desc) (local.get $left))
      (i32.store offset=36 (local.get $desc) (local.get $top))
      (i32.store offset=44 (local.get $desc) (local.get $right))
      (i32.store offset=48 (local.get $desc) (local.get $bottom))
      (call $host_gpu_gl_call (i32.const 0x30014) (local.get $desc) (i32.const 0)))))
  (if (call $d3d_render_park (local.get $result) (i32.const 0)) (then (return)))
  (if (i32.eq (local.get $result) (i32.const 1)) (then (i32.store offset=0 (global.get $reg_base) (i32.const 0)))))

;; UpdateSurface view: width,height,format,bitsWA,pitch,colorStorageGuest,
;; dirtyCounterWA,implicitBackbuffer. Normal texture levels remain CPU authoritative;
;; render-target aliases resolve to the same executor-owned color identity.
(func $d3d9_update_view (param $surface i32) (param $device i32) (param $pool i32) (param $out i32) (result i32)
  (local $p i32) (local $parent i32) (local $mip i32) (local $storage i32)
  (i32.store offset=28 (local.get $out) (i32.const 0))
  (if (i32.eqz (local.get $pool)) (then
    (local.set $p (call $d3ddev_rt_entry (local.get $device)))
    (if (i32.and (i32.ne (local.get $surface) (i32.const 0))
      (i32.eq (local.get $surface) (call $dx_get_wrapper_for_vtbl
        (call $dx_slot_of (local.get $p)) (global.get $DX_VTBL_D3DSURF9)))) (then
      (if (i32.and (load.field DxObject flags (local.get $p)) (i32.const 0x40000000))
        (then (return (i32.const 0))))
      (i32.store (local.get $out) (load.field DxObject width (local.get $p)))
      (i32.store offset=4 (local.get $out) (load.field DxObject height (local.get $p)))
      (i32.store offset=8 (local.get $out) (i32.const 22))
      (i32.store offset=20 (local.get $out) (i32.const 0))
      (i32.store offset=28 (local.get $out) (i32.const 1))
      (return (i32.const 1))))))
  (local.set $storage (call $d3d9_color_storage (local.get $surface)))
  (if (local.get $storage) (then
    (local.set $p (call $g2w (local.get $storage)))
    (if (i32.or (i32.ne (i32.load offset=8 (local.get $p)) (local.get $device))
      (i32.or (i32.ne (i32.load offset=60 (local.get $p)) (local.get $pool))
        (i32.ne (i32.load offset=56 (local.get $p)) (i32.const 0)))) (then (return (i32.const 0))))
    (i32.store (local.get $out) (i32.load offset=20 (local.get $p)))
    (i32.store offset=4 (local.get $out) (i32.load offset=24 (local.get $p)))
    (i32.store offset=8 (local.get $out) (i32.load offset=28 (local.get $p)))
    (i32.store offset=12 (local.get $out) (call $g2w (i32.load offset=40 (local.get $p))))
    (i32.store offset=16 (local.get $out) (i32.load offset=48 (local.get $p)))
    (i32.store offset=20 (local.get $out) (local.get $storage))
    (i32.store offset=24 (local.get $out) (i32.add (local.get $p) (i32.const 68)))
    (return (i32.const 1))))
  (local.set $p (call $d3d9_state_bytes (local.get $surface) (i32.const 20)))
  (if (i32.eqz (local.get $p)) (then (return (i32.const 0))))
  (if (i32.ne (i32.load offset=12 (local.get $p)) (i32.const 0xd3d90001)) (then (return (i32.const 0))))
  (local.set $parent (i32.load offset=8 (local.get $p)))
  (local.set $mip (call $d3d9_texture_mip (local.get $parent) (i32.load offset=16 (local.get $p))))
  (if (i32.eqz (local.get $mip)) (then (return (i32.const 0))))
  (local.set $p (call $g2w (local.get $parent)))
  (if (i32.or (i32.ne (i32.load offset=8 (local.get $p)) (local.get $device))
    (i32.or (i32.ne (i32.load offset=44 (local.get $p)) (local.get $pool))
      (i32.ne (i32.load offset=20 (local.get $mip)) (i32.const 0)))) (then (return (i32.const 0))))
  (i32.store (local.get $out) (i32.load (local.get $mip)))
  (i32.store offset=4 (local.get $out) (i32.load offset=4 (local.get $mip)))
  (i32.store offset=8 (local.get $out) (i32.load offset=36 (local.get $p)))
  (i32.store offset=12 (local.get $out) (call $g2w (i32.load offset=16 (local.get $mip))))
  (i32.store offset=16 (local.get $out) (i32.load offset=8 (local.get $mip)))
  (i32.store offset=20 (local.get $out) (i32.const 0))
  (i32.store offset=24 (local.get $out) (i32.add (local.get $mip) (i32.const 28)))
  (i32.const 1))

(func $d3d9_update_surface (param $device i32) (param $source i32) (param $rect i32) (param $dest i32) (param $point i32)
  (local $allocation i32) (local $s i32) (local $d i32) (local $p i32) (local $desc i32)
  (local $x i32) (local $y i32) (local $w i32) (local $h i32) (local $dx i32) (local $dy i32)
  (local $row i32) (local $bits i32) (local $result i32) (local $format i32)
  (local $block i32) (local $rowbytes i32)
  (i32.store offset=0 (global.get $reg_base) (i32.const 0x8876086c))
  (if (global.get $d3d_render_token) (then
    (local.set $result (call $d3d_render_poll))
    (if (call $d3d_render_park (local.get $result) (i32.const 0)) (then (return)))
    (if (i32.eq (local.get $result) (i32.const 1)) (then (i32.store offset=0 (global.get $reg_base) (i32.const 0)))) (return)))
  (if (i32.eqz (call $d3d9_program_state (local.get $device))) (then (return)))
  (if (i32.eq (local.get $source) (local.get $dest)) (then (return)))
  (local.set $allocation (call $heap_alloc (i32.const 64)))
  (if (i32.eqz (local.get $allocation)) (then (i32.store offset=0 (global.get $reg_base) (i32.const 0x8007000e)) (return)))
  (local.set $s (call $g2w (local.get $allocation))) (local.set $d (i32.add (local.get $s) (i32.const 32)))
  (block $done
    (br_if $done (i32.eqz (call $d3d9_update_view (local.get $source) (local.get $device) (i32.const 2) (local.get $s))))
    (br_if $done (i32.eqz (call $d3d9_update_view (local.get $dest) (local.get $device) (i32.const 0) (local.get $d))))
    (local.set $format (i32.load offset=8 (local.get $s)))
    (br_if $done (i32.ne (local.get $format) (i32.load offset=8 (local.get $d))))
    (local.set $block (call $d3d9_texture_block_bytes (local.get $format)))
    (br_if $done (i32.and (i32.eqz (local.get $block))
      (i32.and (i32.ne (local.get $format) (i32.const 62))
        (i32.and (i32.ne (local.get $format) (i32.const 21)) (i32.ne (local.get $format) (i32.const 22))))))
    (local.set $w (i32.load (local.get $s))) (local.set $h (i32.load offset=4 (local.get $s)))
    (if (local.get $rect) (then
      (local.set $p (call $d3d9_state_bytes (local.get $rect) (i32.const 16))) (br_if $done (i32.eqz (local.get $p)))
      (local.set $x (i32.load (local.get $p))) (local.set $y (i32.load offset=4 (local.get $p)))
      (br_if $done (i32.or (i32.ge_u (local.get $x) (i32.load offset=8 (local.get $p)))
        (i32.ge_u (local.get $y) (i32.load offset=12 (local.get $p)))))
      (br_if $done (i32.or (i32.gt_u (i32.load offset=8 (local.get $p)) (local.get $w))
        (i32.gt_u (i32.load offset=12 (local.get $p)) (local.get $h))))
      (local.set $w (i32.sub (i32.load offset=8 (local.get $p)) (local.get $x)))
      (local.set $h (i32.sub (i32.load offset=12 (local.get $p)) (local.get $y)))))
    (if (local.get $point) (then
      (local.set $p (call $d3d9_state_bytes (local.get $point) (i32.const 8))) (br_if $done (i32.eqz (local.get $p)))
      (local.set $dx (i32.load (local.get $p))) (local.set $dy (i32.load offset=4 (local.get $p)))))
    (br_if $done (i32.or (i32.gt_u (local.get $dx) (i32.load (local.get $d)))
      (i32.gt_u (local.get $dy) (i32.load offset=4 (local.get $d)))))
    (br_if $done (i32.or (i32.gt_u (local.get $w) (i32.sub (i32.load (local.get $d)) (local.get $dx)))
      (i32.gt_u (local.get $h) (i32.sub (i32.load offset=4 (local.get $d)) (local.get $dy)))))
    (if (local.get $block) (then
      ;; Blocks may include padding at a mip edge, never unrelated texels.
      (br_if $done (i32.and (i32.or (i32.or (local.get $x) (local.get $y))
        (i32.or (local.get $dx) (local.get $dy))) (i32.const 3)))
      (if (i32.and (local.get $w) (i32.const 3)) (then
        (br_if $done (i32.or (i32.ne (i32.add (local.get $x) (local.get $w)) (i32.load (local.get $s)))
          (i32.ne (i32.add (local.get $dx) (local.get $w)) (i32.load (local.get $d)))))))
      (if (i32.and (local.get $h) (i32.const 3)) (then
        (br_if $done (i32.or (i32.ne (i32.add (local.get $y) (local.get $h)) (i32.load offset=4 (local.get $s)))
          (i32.ne (i32.add (local.get $dy) (local.get $h)) (i32.load offset=4 (local.get $d)))))))))
    (local.set $bits (i32.add (i32.load offset=12 (local.get $s))
      (i32.add (i32.mul (local.get $y) (i32.load offset=16 (local.get $s))) (i32.mul (local.get $x) (i32.const 4)))))
    (if (i32.or (i32.load offset=20 (local.get $d)) (i32.load offset=28 (local.get $d))) (then
      (local.set $desc (call $d3d9_gpu_descriptor (local.get $device)))
      (i32.store offset=24 (local.get $desc) (i32.load offset=20 (local.get $d)))
      (i32.store offset=28 (local.get $desc) (local.get $bits))
      (i32.store offset=32 (local.get $desc) (i32.load offset=16 (local.get $s)))
      (i32.store offset=36 (local.get $desc) (local.get $dx))
      (i32.store offset=44 (local.get $desc) (local.get $dy))
      (i32.store offset=48 (local.get $desc) (local.get $w))
      (i32.store offset=52 (local.get $desc) (local.get $h))
      (i32.store offset=56 (local.get $desc) (local.get $format))
      (local.set $result (call $host_gpu_gl_call (i32.const 0x30015) (local.get $desc) (i32.const 0))))
    (else
      (local.set $rowbytes (i32.mul (local.get $w) (i32.const 4)))
      (local.set $dx (i32.mul (local.get $dx) (i32.const 4)))
      (if (local.get $block) (then
        (local.set $rowbytes (call $d3d9_texture_pitch (local.get $w) (local.get $format)))
        (local.set $h (call $d3d9_texture_rows (local.get $h) (local.get $format)))
        (local.set $dx (i32.mul (i32.shr_u (local.get $dx) (i32.const 4)) (local.get $block)))
        (local.set $dy (i32.shr_u (local.get $dy) (i32.const 2)))
        (local.set $bits (i32.add (i32.load offset=12 (local.get $s))
          (i32.add (i32.mul (i32.shr_u (local.get $y) (i32.const 2)) (i32.load offset=16 (local.get $s)))
            (i32.mul (i32.shr_u (local.get $x) (i32.const 2)) (local.get $block)))))))
      (loop $rows
        (memory.copy (i32.add (i32.load offset=12 (local.get $d))
          (i32.add (i32.mul (i32.add (local.get $dy) (local.get $row)) (i32.load offset=16 (local.get $d))) (local.get $dx)))
          (i32.add (local.get $bits) (i32.mul (local.get $row) (i32.load offset=16 (local.get $s)))) (local.get $rowbytes))
        (local.set $row (i32.add (local.get $row) (i32.const 1))) (br_if $rows (i32.lt_u (local.get $row) (local.get $h))))
      (local.set $p (i32.load offset=24 (local.get $d)))
      (i32.store (local.get $p) (i32.add (i32.load (local.get $p)) (i32.const 1)))
      (local.set $result (i32.const 1))))
    (if (i32.eq (local.get $result) (i32.const 1)) (then (i32.store offset=0 (global.get $reg_base) (i32.const 0)))))
  (call $heap_free (local.get $allocation))
  (drop (call $d3d_render_park (local.get $result) (i32.const 0))))

;; Dimensions of bound RT0; presentation always retains the implicit slot.
(func $d3d9_color_extent (param $device i32) (param $height i32) (result i32)
  (local $state i32) (local $surface i32) (local $rt i32)
  (local.set $state (call $d3d9_program_state (local.get $device)))
  (if (i32.eqz (local.get $state)) (then (return (i32.const 0))))
  (local.set $surface (call $gl32 (i32.add (local.get $state) (i32.const 22020))))
  (if (local.get $surface) (then
    (return (call $gl32 (i32.add (local.get $surface) (select (i32.const 24) (i32.const 20) (local.get $height)))))))
  (local.set $rt (call $d3ddev_rt_entry (local.get $device)))
  (select (load.field DxObject height (local.get $rt)) (load.field DxObject width (local.get $rt)) (local.get $height)))

(func $d3d9_color_binding (param $device i32) (param $index i32) (param $surface i32)
  (local $state i32) (local $old i32) (local $wa i32) (local $rt i32) (local $storage i32) (local $parent i32)
  (i32.store offset=0 (global.get $reg_base) (i32.const 0x8876086c))
  (if (i32.or (local.get $index) (i32.eqz (local.get $surface))) (then (return)))
  (local.set $state (call $d3d9_program_state (local.get $device)))
  (if (i32.eqz (local.get $state)) (then (return)))
  (local.set $state (call $g2w (local.get $state)))
  (local.set $old (i32.load offset=22020 (local.get $state)))
  (local.set $storage (call $d3d9_color_storage (local.get $surface)))
  (if (local.get $storage) (then
    (local.set $surface (local.get $storage))
    (local.set $wa (call $g2w (local.get $surface)))
    (if (i32.or (i32.ne (i32.load offset=8 (local.get $wa)) (local.get $device))
      (i32.or (i32.ne (i32.load offset=64 (local.get $wa)) (i32.const 1))
        (i32.ne (i32.load offset=56 (local.get $wa)) (i32.const 0)))) (then (return))))
  (else
    (local.set $rt (call $d3ddev_rt_entry (local.get $device)))
    (if (i32.ne (local.get $surface) (call $dx_get_wrapper_for_vtbl
      (call $dx_slot_of (local.get $rt)) (global.get $DX_VTBL_D3DSURF9))) (then (return)))
    (local.set $surface (i32.const 0))))
  (if (i32.and (i32.ne (local.get $old) (i32.const 0)) (i32.ne (local.get $old) (local.get $surface))) (then
    (local.set $wa (call $g2w (local.get $old)))
    (if (i32.and (i32.eqz (i32.load offset=72 (local.get $wa)))
      (i32.and (i32.eqz (i32.load offset=4 (local.get $wa))) (i32.eq (i32.load offset=16 (local.get $wa)) (i32.const 1)))) (then
      (if (i32.eqz (call $d3d9_depth_retire (local.get $old))) (then (return)))))))
  (if (local.get $surface) (then
    (local.set $wa (call $g2w (local.get $surface)))
    (local.set $parent (i32.load offset=72 (local.get $wa)))
    (if (local.get $parent) (then
      (call $gs32 (i32.add (local.get $parent) (i32.const 20))
        (i32.add (call $gl32 (i32.add (local.get $parent) (i32.const 20))) (i32.const 1)))))
    (i32.store offset=16 (local.get $wa) (i32.add (i32.load offset=16 (local.get $wa)) (i32.const 1)))))
  (i32.store offset=22020 (local.get $state) (local.get $surface))
  (call $d3d9_color_unbind (local.get $old))
  (memory.fill (i32.add (local.get $state) (i32.const 21728)) (i32.const 0) (i32.const 24))
  (memory.fill (i32.add (local.get $state) (i32.const 22000)) (i32.const 0) (i32.const 20))
  (i32.store offset=0 (global.get $reg_base) (i32.const 0)))

(func $d3d9_color_desc (param $surface i32) (param $out i32)
  (local $wa i32) (local $dest i32)
  (i32.store offset=0 (global.get $reg_base) (i32.const 0x8876086c))
  (local.set $dest (call $d3d9_state_bytes (local.get $out) (i32.const 32)))
  (if (i32.eqz (local.get $dest)) (then (return)))
  (local.set $wa (call $g2w (local.get $surface)))
  (memory.fill (local.get $dest) (i32.const 0) (i32.const 32))
  (i32.store (local.get $dest) (i32.load offset=28 (local.get $wa)))
  (i32.store offset=4 (local.get $dest) (i32.const 1))
  (i32.store offset=8 (local.get $dest) (i32.load offset=64 (local.get $wa)))
  (i32.store offset=12 (local.get $dest) (i32.load offset=60 (local.get $wa)))
  (i32.store offset=24 (local.get $dest) (i32.load offset=20 (local.get $wa)))
  (i32.store offset=28 (local.get $dest) (i32.load offset=24 (local.get $wa)))
  (i32.store offset=0 (global.get $reg_base) (i32.const 0)))

;; Return only after the ordered backend read/write has completed. The caller
;; retains its original stack and arguments while the normal render token parks.
(func $d3d9_color_sync (param $surface i32) (param $upload i32) (result i32)
  (local $result i32) (local $wa i32)
  (local.set $wa (call $g2w (local.get $surface)))
  (local.set $result (if (result i32) (global.get $d3d_render_token)
    (then (call $d3d_render_poll))
    (else (call $host_gpu_gl_call (select (i32.const 0x30011) (i32.const 0x30010) (local.get $upload))
      (local.get $wa) (i32.load offset=8 (local.get $wa))))))
  (if (call $d3d_render_park (local.get $result) (i32.const 0)) (then (return (i32.const 0))))
  (i32.eq (local.get $result) (i32.const 1)))

(func $d3d9_color_lock (param $surface i32) (param $out i32) (param $rect i32) (param $flags i32)
  (local $wa i32) (local $dest i32) (local $rw i32) (local $left i32) (local $top i32)
  (i32.store offset=0 (global.get $reg_base) (i32.const 0x8876086c))
  (local.set $wa (call $g2w (local.get $surface)))
  (local.set $dest (call $d3d9_state_bytes (local.get $out) (i32.const 8)))
  (if (i32.or (i32.eqz (local.get $dest)) (i32.or (i32.eqz (i32.load offset=32 (local.get $wa)))
    (i32.ne (i32.load offset=56 (local.get $wa)) (i32.const 0)))) (then (return)))
  ;; READONLY and NOSYSLOCK are implemented; never silently accept DISCARD,
  ;; NOOVERWRITE or a nonblocking request that would actually wait.
  (if (i32.and (local.get $flags) (i32.const 0xfffff7ef)) (then (return)))
  (if (local.get $rect) (then
    (local.set $rw (call $d3d9_state_bytes (local.get $rect) (i32.const 16)))
    (if (i32.eqz (local.get $rw)) (then (return)))
    (local.set $left (i32.load (local.get $rw))) (local.set $top (i32.load offset=4 (local.get $rw)))
    (if (i32.ge_u (local.get $left) (i32.load offset=8 (local.get $rw))) (then (return)))
    (if (i32.ge_u (local.get $top) (i32.load offset=12 (local.get $rw))) (then (return)))
    (if (i32.gt_u (i32.load offset=8 (local.get $rw)) (i32.load offset=20 (local.get $wa))) (then (return)))
    (if (i32.gt_u (i32.load offset=12 (local.get $rw)) (i32.load offset=24 (local.get $wa))) (then (return)))))
  (if (i32.eqz (call $d3d9_color_sync (local.get $surface) (i32.const 0))) (then (return)))
  (i32.store offset=56 (local.get $wa) (i32.or (local.get $flags) (i32.const 1)))
  (i32.store (local.get $dest) (i32.load offset=48 (local.get $wa)))
  (i32.store offset=4 (local.get $dest) (i32.add (i32.load offset=40 (local.get $wa))
    (i32.add (i32.mul (local.get $top) (i32.load offset=48 (local.get $wa))) (i32.mul (local.get $left) (i32.const 4)))))
  (i32.store offset=0 (global.get $reg_base) (i32.const 0)))

(func $d3d9_color_unlock (param $surface i32)
  (local $wa i32)
  (i32.store offset=0 (global.get $reg_base) (i32.const 0x8876086c))
  (local.set $wa (call $g2w (local.get $surface)))
  (if (i32.eqz (i32.load offset=56 (local.get $wa))) (then (return)))
  (if (i32.eqz (i32.and (i32.load offset=56 (local.get $wa)) (i32.const 16))) (then
    (if (i32.eqz (call $d3d9_color_sync (local.get $surface) (i32.const 1))) (then (return)))
    (i32.store offset=68 (local.get $wa) (i32.add (i32.load offset=68 (local.get $wa)) (i32.const 1)))))
  (i32.store offset=56 (local.get $wa) (i32.const 0)) (i32.store offset=0 (global.get $reg_base) (i32.const 0)))

(func $d3d9_color_copy (param $device i32) (param $source i32) (param $dest i32)
  (local $src i32) (local $dst i32) (local $rt i32) (local $result i32)
  (i32.store offset=0 (global.get $reg_base) (i32.const 0x8876086c))
  (if (i32.eqz (call $d3d9_program_state (local.get $device))) (then (return)))
  (if (i32.eqz (call $d3d9_is_color_surface (local.get $dest))) (then (return)))
  (local.set $dst (call $g2w (local.get $dest)))
  (if (i32.ne (i32.load offset=8 (local.get $dst)) (local.get $device)) (then (return)))
  (if (i32.ne (i32.load offset=60 (local.get $dst)) (i32.const 2)) (then (return)))
  (if (i32.load offset=56 (local.get $dst)) (then (return)))
  (local.set $src (call $d3d9_color_storage (local.get $source)))
  (if (local.get $src) (then (local.set $source (local.get $src))))
  (if (i32.eqz (call $d3d9_is_color_surface (local.get $source))) (then
    (local.set $rt (call $d3ddev_rt_entry (local.get $device)))
    (if (i32.ne (local.get $source) (call $dx_get_wrapper_for_vtbl
      (call $dx_slot_of (local.get $rt)) (global.get $DX_VTBL_D3DSURF9))) (then (return)))
    (if (i32.ne (i32.load offset=28 (local.get $dst)) (i32.const 22)) (then (return)))
    (if (i32.ne (i32.load offset=20 (local.get $dst)) (load.field DxObject width (local.get $rt))) (then (return)))
    (if (i32.ne (i32.load offset=24 (local.get $dst)) (load.field DxObject height (local.get $rt))) (then (return)))
    (local.set $result (if (result i32) (global.get $d3d_render_token)
      (then (call $d3d_render_poll))
      (else (call $host_gpu_gl_call (i32.const 0x30012) (call $d3d9_gpu_descriptor (local.get $device)) (local.get $dst)))))
    (if (call $d3d_render_park (local.get $result) (i32.const 0)) (then (return)))
    (if (i32.eq (local.get $result) (i32.const 1)) (then (i32.store offset=0 (global.get $reg_base) (i32.const 0))))
    (return)))
  (local.set $src (call $g2w (local.get $source))) (local.set $dst (call $g2w (local.get $dest)))
  (if (i32.or (i32.ne (i32.load offset=8 (local.get $src)) (local.get $device))
    (i32.ne (i32.load offset=8 (local.get $dst)) (local.get $device))) (then (return)))
  (if (i32.or (i32.ne (i32.load offset=64 (local.get $src)) (i32.const 1))
    (i32.ne (i32.load offset=60 (local.get $dst)) (i32.const 2))) (then (return)))
  (if (i32.or (i32.load offset=56 (local.get $src)) (i32.load offset=56 (local.get $dst))) (then (return)))
  (if (i32.or (i32.ne (i32.load offset=20 (local.get $src)) (i32.load offset=20 (local.get $dst)))
    (i32.or (i32.ne (i32.load offset=24 (local.get $src)) (i32.load offset=24 (local.get $dst)))
      (i32.ne (i32.load offset=28 (local.get $src)) (i32.load offset=28 (local.get $dst))))) (then (return)))
  (if (i32.eqz (call $d3d9_color_sync (local.get $source) (i32.const 0))) (then (return)))
  (memory.copy (call $g2w (i32.load offset=40 (local.get $dst)))
    (call $g2w (i32.load offset=40 (local.get $src))) (i32.load offset=52 (local.get $src)))
  (i32.store offset=68 (local.get $dst) (i32.add (i32.load offset=68 (local.get $dst)) (i32.const 1)))
  (i32.store offset=0 (global.get $reg_base) (i32.const 0)))

;; StretchRect needs TWO ordered backend calls, and the park protocol carries
;; one token, so the phase has to be remembered across the re-entry a park
;; causes. Stage 0 downloads the source (the backend owns its pixels -- the
;; guest just rendered into it); stage 1 copies CPU-side and uploads the
;; destination through the same 0x30015 path UpdateSurface uses. A park in
;; stage 0 re-enters with the stage still 0, so the poll lands on the readback
;; it belongs to; a park in stage 1 re-enters with stage 1 and skips the
;; readback rather than re-issuing it and polling the wrong operation.
(global $d3d9_stretch_stage (mut i32) (i32.const 0))

;; A device's implicit backbuffer has a DxObject wrapper rather than the
;; heap color-surface header. Upload to backend target zero explicitly: the
;; currently bound render target may be a different surface.
(func $d3d9_stretch_to_backbuffer (param $device i32) (param $source i32) (param $dest i32)
  (param $name_ptr i32)
  (local $src i32) (local $rt i32) (local $desc i32) (local $result i32)
  (if (i32.ne (call $d3d9_backbuffer_owner (local.get $dest)) (local.get $device)) (then (return)))
  (if (i32.eqz (call $d3d9_is_color_surface (local.get $source)))
    (then (call $crash_unimplemented (local.get $name_ptr)) (return)))
  (local.set $src (call $g2w (local.get $source)))
  (local.set $rt (call $dx_from_this (local.get $dest)))
  (if (i32.ne (i32.load offset=8 (local.get $src)) (local.get $device)) (then (return)))
  (if (i32.or (i32.load offset=56 (local.get $src)) (i32.load offset=60 (local.get $src))) (then (return)))
  (if (i32.and (load.field DxObject flags (local.get $rt)) (i32.const 0x44000000)) (then (return)))
  ;; Equal-size X8R8G8B8 copies use the same transfer protocol as UpdateSurface.
  ;; Scaling, conversion, and other filters remain explicit unsupported paths.
  (if (i32.or (i32.ne (i32.load offset=28 (local.get $src)) (i32.const 22))
    (i32.or (i32.ne (i32.load offset=20 (local.get $src)) (load.field DxObject width (local.get $rt)))
      (i32.ne (i32.load offset=24 (local.get $src)) (load.field DxObject height (local.get $rt)))))
    (then (call $crash_unimplemented (local.get $name_ptr)) (return)))
  (if (i32.eqz (global.get $d3d9_stretch_stage)) (then
    (if (i32.eqz (call $d3d9_color_sync (local.get $source) (i32.const 0))) (then (return)))
    (global.set $d3d9_stretch_stage (i32.const 1))))
  (local.set $result (if (result i32) (global.get $d3d_render_token)
    (then (call $d3d_render_poll))
    (else
      (local.set $desc (call $d3d9_gpu_descriptor (local.get $device)))
      (i32.store offset=24 (local.get $desc) (i32.const 0))
      (i32.store offset=28 (local.get $desc) (call $g2w (i32.load offset=40 (local.get $src))))
      (i32.store offset=32 (local.get $desc) (i32.load offset=48 (local.get $src)))
      (i32.store offset=36 (local.get $desc) (i32.const 0))
      (i32.store offset=44 (local.get $desc) (i32.const 0))
      (i32.store offset=48 (local.get $desc) (i32.load offset=20 (local.get $src)))
      (i32.store offset=52 (local.get $desc) (i32.load offset=24 (local.get $src)))
      (i32.store offset=56 (local.get $desc) (i32.const 22))
      (call $host_gpu_gl_call (i32.const 0x30015) (local.get $desc) (i32.const 0)))))
  (if (call $d3d_render_park (local.get $result) (i32.const 0)) (then (return)))
  (global.set $d3d9_stretch_stage (i32.const 0))
  (if (i32.eq (local.get $result) (i32.const 1))
    (then (i32.store offset=0 (global.get $reg_base) (i32.const 0)))))

;; Only the shape guests actually ask for is implemented: whole surface to
;; whole surface, same size, same format, no filter. Everything else --
;; a real stretch, a format conversion, a sub-rectangle -- crashes instead of
;; returning a picture that is silently wrong, because a blit that lands but
;; is the wrong size reads as a texturing bug a long way from here.
;; Black & White 2's land loader is the caller: d3dx9_25's
;; D3DXLoadSurfaceFromSurface copies the 512x512 A8R8G8B8 terrain render
;; target into a freshly created one with NULL rects and D3DTEXF_NONE.
(func $d3d9_color_stretch (param $device i32) (param $source i32) (param $srcrect i32)
  (param $dest i32) (param $dstrect i32) (param $filter i32) (param $name_ptr i32)
  (local $src i32) (local $dst i32) (local $storage i32) (local $desc i32) (local $result i32)
  (i32.store offset=0 (global.get $reg_base) (i32.const 0x8876086c))
  (if (i32.eqz (call $d3d9_program_state (local.get $device))) (then (return)))
  (local.set $storage (call $d3d9_color_storage (local.get $source)))
  (if (local.get $storage) (then (local.set $source (local.get $storage))))
  (local.set $storage (call $d3d9_color_storage (local.get $dest)))
  (if (local.get $storage) (then (local.set $dest (local.get $storage))))
  (if (i32.or (i32.ne (local.get $srcrect) (i32.const 0))
    (i32.or (i32.ne (local.get $dstrect) (i32.const 0)) (i32.ne (local.get $filter) (i32.const 0))))
    (then (call $crash_unimplemented (local.get $name_ptr)) (return)))
  (if (call $d3d9_backbuffer_owner (local.get $dest)) (then
    (call $d3d9_stretch_to_backbuffer (local.get $device) (local.get $source) (local.get $dest) (local.get $name_ptr))
    (return)))
  (if (i32.or (i32.eqz (call $d3d9_is_color_surface (local.get $source)))
    (i32.eqz (call $d3d9_is_color_surface (local.get $dest))))
    (then (call $crash_unimplemented (local.get $name_ptr)) (return)))
  ;; Same surface, a locked surface, a foreign device or a non-DEFAULT pool are
  ;; all D3DERR_INVALIDCALL on real hardware, not gaps in this implementation.
  (if (i32.eq (local.get $source) (local.get $dest)) (then (return)))
  (local.set $src (call $g2w (local.get $source)))
  (local.set $dst (call $g2w (local.get $dest)))
  (if (i32.or (i32.ne (i32.load offset=8 (local.get $src)) (local.get $device))
    (i32.ne (i32.load offset=8 (local.get $dst)) (local.get $device))) (then (return)))
  (if (i32.or (i32.load offset=56 (local.get $src)) (i32.load offset=56 (local.get $dst))) (then (return)))
  (if (i32.or (i32.load offset=60 (local.get $src)) (i32.load offset=60 (local.get $dst))) (then (return)))
  (if (i32.ne (i32.load offset=64 (local.get $dst)) (i32.const 1)) (then (return)))
  (if (i32.or (i32.ne (i32.load offset=20 (local.get $src)) (i32.load offset=20 (local.get $dst)))
    (i32.or (i32.ne (i32.load offset=24 (local.get $src)) (i32.load offset=24 (local.get $dst)))
      (i32.ne (i32.load offset=28 (local.get $src)) (i32.load offset=28 (local.get $dst)))))
    (then (call $crash_unimplemented (local.get $name_ptr)) (return)))
  (if (i32.eqz (global.get $d3d9_stretch_stage)) (then
    (if (i32.eqz (call $d3d9_color_sync (local.get $source) (i32.const 0))) (then (return)))
    (global.set $d3d9_stretch_stage (i32.const 1))))
  (memory.copy (call $g2w (i32.load offset=40 (local.get $dst)))
    (call $g2w (i32.load offset=40 (local.get $src))) (i32.load offset=52 (local.get $src)))
  (local.set $result (if (result i32) (global.get $d3d_render_token)
    (then (call $d3d_render_poll))
    (else
      (local.set $desc (call $d3d9_gpu_descriptor (local.get $device)))
      (i32.store offset=24 (local.get $desc) (local.get $dest))
      (i32.store offset=28 (local.get $desc) (call $g2w (i32.load offset=40 (local.get $dst))))
      (i32.store offset=32 (local.get $desc) (i32.load offset=48 (local.get $dst)))
      (i32.store offset=36 (local.get $desc) (i32.const 0))
      (i32.store offset=44 (local.get $desc) (i32.const 0))
      (i32.store offset=48 (local.get $desc) (i32.load offset=20 (local.get $dst)))
      (i32.store offset=52 (local.get $desc) (i32.load offset=24 (local.get $dst)))
      (i32.store offset=56 (local.get $desc) (i32.load offset=28 (local.get $dst)))
      (call $host_gpu_gl_call (i32.const 0x30015) (local.get $desc) (i32.const 0)))))
  (if (call $d3d_render_park (local.get $result) (i32.const 0)) (then (return)))
  (global.set $d3d9_stretch_stage (i32.const 0))
  (if (i32.eq (local.get $result) (i32.const 1)) (then
    (i32.store offset=68 (local.get $dst) (i32.add (i32.load offset=68 (local.get $dst)) (i32.const 1)))
    (i32.store offset=0 (global.get $reg_base) (i32.const 0)))))
